{{- if .Values.selfapp.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: meta-infrastructure
  namespace: "{{ .Release.Namespace }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "meta infra services such as base helm charts"
  orphanedResources:
    warn: false
  sourceRepos:
    - "*"
  destinations:
    - server: "*"
      namespace: '*'
      name: '*'
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
{{- end -}}