{{- if .Values.selfapp.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  project: default
  source:
    repoURL: "git@github.com:{{ .Values.selfapp.repo }}.git"
    targetRevision: "{{ .Values.selfapp.commit }}"
    path: k8s/argocd
    helm:
      parameters:
      - name: "selfapp.enabled"
        value: "true"
      - name: "selfapp.sshkey"
        value: {{ .Values.selfapp.sshkey | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{ .Release.Namespace }}"
{{- end -}}