{{- if .Values.selfapp.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: "{{ .Release.Namespace }}"
spec:
  project: default
  source:
    chart: contour
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "11.0.0"
    helm:
      releaseName: contour
  destination:
    server: "https://kubernetes.default.svc"
    namespace: contour
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{- end -}}