{{- if .Values.selfapp.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "cert-manager"
  namespace: "{{ .Release.Namespace }}"
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: "https://charts.jetstack.io"
    targetRevision: "1.10.2"
    helm:
      values: |-
        installCRDs: true
      releaseName: cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: "cert-manager"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end -}}