
{{ if $.Values.global.tls.enabled }}
---
apiVersion: v1
kind: Secret
type: "kubernetes.io/tls"
metadata:
  name: "argo-cert"
data:
    tls.key: 
    tls.crt: 
{{ end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    homelab/ingress-type: "self-managed"
  {{ if $.Values.global.ingressAnnotations }}
    {{- range $k, $v := $.Values.global.ingressAnnotations }}
    {{ $k -}}: "{{- $v -}}"
    {{- end }}
  {{ end }}
spec:
  rules:
    - host: "argocd.{{ .Values.global.domain }}"
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  number: 80
            path: /
            pathType: Prefix
  # {{ if $.Values.global.tls.enabled }}
  # tls:
  #   - secretName: "argo-cert"
  #     hosts:
  #       - "argocd.{{ $.Values.global.domain }}"
  # {{ end }}
