{{- if .Values.selfapp.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: "{{ .Release.Namespace }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure
  sourceRepos:
  - '*'
  destinations:
  - server: https://kubernetes.default.svc
{{- end -}}