---
apiVersion: batch/v1
kind: Job
metadata:
  name: "user-generation"
  namespace: "{{ .Release.Namespace }}"
spec:
  template:
    metadata:
      annotations:
        checksum/run-sh: "{{ include "pg-users.entry" . | sha256sum }}"
        checksum/main-tf: "{{ include "pg-users.terraform" . | sha256sum }}"
        checksum/users-tfvars: "{{ (print "db_users = " ( .Values.userGeneration.users | toJson  )) | sha256sum }}"
    spec:
      serviceAccount: "{{ .Release.Name }}"
      serviceAccountName: "{{ .Release.Name }}"
      volumes:
        - name: tffiles
          secret:
            secretName: "user-generation-tf"
      containers:
        - name: base
          image: "hashicorp/terraform:{{ .Values.userGeneration.tfVersion }}"
          command:
            - sh
            - /app/run.sh
          volumeMounts:
            - mountPath: /app
              name: tffiles
          env:
            - name: TF_LOG_PATH
              value: /tmp/terraform.log
            - name: TF_INPUT
              value: "0"
            - name: TF_DATA_DIR
              value: /tmp/.terraform
            - name: TF_IN_AUTOMATION
              value: "1"
            - name: TF_VAR_db_host
              value: "postgres.{{ .Release.Namespace }}.svc.cluster.local"
            - name: TF_VAR_db_username
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgresql.auth.existingSecret }}"
                  key: "username"
            - name: TF_VAR_db_password
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgresql.auth.existingSecret }}"
                  key: "password"
      restartPolicy: Never
  backoffLimit: 2
