---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-scale-nfs-family-storage
provisioner: nfs.csi.k8s.io
parameters:
  server: truenas.local
  share: /mnt/EightTerra/FamilyStorage
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-scale-nfs-k3s-cluster-general
provisioner: nfs.csi.k8s.io
parameters:
  server: truenas.local
  share: /mnt/EightTerra/k3s-cluster
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
