global:
  email: "ariel@sosnovsky.ca"
  timezone: America/Toronto
  domain: ""
  tls:
    enabled: false
    issuer: ""
    acmeServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
    skipTLSVerify: "false"
  nfs:
    storageClass: "nfs-generic"
    server: "changme"
    share: "changeme"
