ns:
    argocd: plugin-argo-cd
global:
    nfs:
        storageClassName: ""
        storageProvider: ""

composeApp:
    gitops:
        repo: git@github.com:asosnovsky/helm-charts.git
        revision: main