reverseProxy: {}
services:
  - prefix: "argocd.core"
    service: "argocd-server"
    namespace: "argocd"
  - prefix: "demo"
    service: "dummy-app"
    namespace: "apps-ingresses"
  - prefix: "nextcloud"
    service: "nextcloud"
    namespace: "apps-nextcloud"
    port: 8080
    middleware: "apps-nextcloud-nextcloud"