reverseProxy: {}
services:
  - prefix: "argocd.core"
    service: "argocd-server"
    namespace: "argocd"
  - prefix: "demo"
    service: "dummy-app"
    namespace: "apps-ingresses"
    middleware: "apps-ingresses-forwardauth-authentik"
cloudflare:
  enabled: false
  tokenSecretName: ~
  tokenSecretKey: ~
