global:
  tls:
    enabled: true
reverseProxy:
  castle:
    ip: "10.0.12.1"
    port: "80"
    overrides:
      icon: http://10.0.12.1:80/static/icons/favicon.ico

  kuma:
    ip: "10.0.12.1"
    port: "3001"
    overrides:
      icon: "https://kuma.home.sosnovsky.ca/apple-touch-icon.png"

  basement:
    ip: "10.0.12.2"
    port: "80"
    overrides:
      icon: http://10.0.12.2:80/static/icons/favicon.ico

  pitorrent:
    ip: "10.0.10.3"
    port: "8080"
    overrides:
      middleware: "apps-ingresses-chain-authentik"
      group: "Video Hosting"
  
  esphome:
    ip: "10.0.10.4"
    port: "6052"
    overrides:
      middleware: "apps-ingresses-chain-authentik"

  scrypted:
    ip: "10.0.10.4"
    port: "11080"
    overrides:
      group: "Cameras"

cloudflare:
  enabled: true

staticFiles:
  mainDomain: []
  secondaryDomain: 
    - path: "ads.txt"
      content: |
        google.com, pub-6915532978483380, DIRECT, f08c47fec0942fa0