---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Namespace }}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "get"]
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ .Release.Name }}"
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}"
    namespace: "{{ .Release.Namespace }}"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secrets
spec:
  provider:
    kubernetes:
      remoteNamespace: "{{ .Release.Namespace }}"
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: "{{ .Release.Namespace }}"
      auth:
        serviceAccount:
          name: "{{ .Release.Namespace }}"
          namespace: "{{ .Release.Namespace }}"
