global: {}

registry:
  ip: 10.0.100.101
  image: registry:2

ns:
  metallb: "change-me"
  argocd: "change-me"

gitops:
  type: git
  url: http://minipc1.lab.internal:3000/ari/homelab.git
  revision: main
  data:
    username: argocd
    password: "change-me"

repos:
  github-helm-charts:
    type: git
    url: git@github.com:asosnovsky/helm-charts.git
    data:
      sshPrivateKey: "change-me"

metallb:
  addresses:
    - 10.0.100.1-10.0.100.255

enabledClusterSecretStores:
  - secrets
