userGeneration:
  tfVersion: "1.3.7"
  users:
    - nextcloud
    - authentik
    - radarr
    - sonarr
    - prowlarr
    - immich
    - readarr
  users_dbs:
    radarr: [log, cache]
    sonarr: [log, cache]
    prowlarr: [log, cache]
    readarr: [log, cache]
    bazarr: [log, cache]

postgresSecret: ""

terraform:
  cyrilgdnPostgresql:
    tag: 1.18.0