userGeneration:
  tfVersion: "1.3.7"
  users:
    - nextcloud
    - authentik
    - radarr
    - sonarr
    - prowlarr
    - immich
  users_dbs:
    radarr: [log]
    sonarr: [log]
    prowlarr: [log]

postgresSecret: ""

terraform:
  cyrilgdnPostgresql:
    tag: 1.18.0