image: "koenkk/zigbee2mqtt"
tag: "latest-dev"
global:
    timezone: changeme
    mqtt:
        host: ""

affinity:
    nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
            -   weight: 1
                preference:
                    matchExpressions:
                        -   key: hardware/zigbee
                            operator: In
                            values:
                                - "yes"
persistence:
    data_path:
        claimName: ""

devicePath: /dev/ttyUSB0

resources:
    requests:
        memory: "500Mi"
        cpu: "150m"
    limits:
        memory: "500Mi"
        cpu: "150m"
