repositories:
    -   name: prometheus-community
        url: https://prometheus-community.github.io/helm-charts
    -   name: grafana
        url: https://grafana.github.io/helm-charts
    -   name: external-secrets
        url: https://charts.external-secrets.io 
    -   name: metallb
        url: https://metallb.github.io/metallb
# helm install metallb 
releases:
    -   name: external-secrets
        namespace: plugin-external-secrets
        chart: external-secrets/external-secrets
        version: "0.11.0"
    # -   name: metallb
    #     namespace: plugin-metallb
    #     chart: metallb/metallb
    #     version: "0.14.9"
    # -   name: plugin-infrastructure
    #     namespace: metallb
    #     chart: ./k8s/infrastructure
    #     values:
    #         - ./k8s/infrastructure/values.yaml
    #     needs:
    #         - plugin-metallb/metallb
    #         - plugin-external-secrets/external-secrets
    # -   name: loki
    #     namespace: plugin-monitoring
    #     chart: grafana/loki-stack
    #     version: "2.10.2"
    #     values:
    #         - helmfile/values-loki-stack.yaml
    # -   name: kube-prometheus-stack
    #     namespace: plugin-monitoring
    #     chart: prometheus-community/kube-prometheus-stack
    #     version: "68.2.1"
    #     values:
    #         - helmfile/values-kube-prometheus-stack.yaml
    #     needs:
    #         - plugin-monitoring/prometheus-operator-crds
    # -   name: infra
    #     chart: ./charts/infra
    #     namespace: default
    #     values:
    #         - charts/infra/values.yaml
    #         - charts/infra/environments/sibli-gcp-values.yaml
    #     needs: 
    #         - plugin-monitoring/kube-prometheus-stack
    #         - plugin-external-secrets/external-secrets