apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      {{ .Release.Name }}/app: frigate
  template:
    metadata:
      labels:
        {{ .Release.Name }}/app: frigate
    spec:
      volumes:
        {{- if .Values.persistence.media_path.enabled }}
        -   name: media-path
            persistentVolumeClaim:
              claimName: {{ .Values.persistence.media_path.claimName }}
        {{- end }}
        {{- if .Values.persistence.conf_path.enabled }}
        -   name: conf-path
            persistentVolumeClaim:
              claimName: {{ .Values.persistence.conf_path.claimName }}
        {{- end }}
      containers:
        -   name: main
            image: "{{ .Values.image }}:{{ .Values.tag | default .Chart.AppVersion }}"
            resources: 
              {{- .Values.resources | toYaml | nindent 14}}

            livenessProbe:
              httpGet:
                path: /
                port: http
                scheme: HTTP
              initialDelaySeconds: 10
              failureThreshold: 10
              timeoutSeconds: 30
            readinessProbe:
              httpGet:
                path: /
                port: http
                scheme: HTTP
              initialDelaySeconds: 10
              failureThreshold: 10
              timeoutSeconds: 30
            startupProbe:
              httpGet:
                path: /
                port: http
                scheme: HTTP
              failureThreshold: 60
              periodSeconds: 15
            ports:
              -   containerPort: 5000
                  name: http
              -   containerPort: 8554
                  name: rtsp
              -   containerPort: 8555
                  name: webrtc-tcp
                  protocol: TCP
              -   containerPort: 8555
                  name: webrtc-udp
                  protocol: UDP
            volumeMounts:
        {{- if .Values.persistence.media_path.enabled }}
              -   name: media-path
                  mountPath: /media/frigate
        {{ end }}
        {{- if .Values.persistence.conf_path.enabled }}
              -   name: conf-path
                  mountPath: /config
        {{ end }}
