---
kind: Service
apiVersion: v1
metadata:
  name: go2rtc-lb
spec:
  selector:
    homelab/app: go2rtc
  type: LoadBalancer
  ports:
    - port: 8554
      targetPort: 8554
      name: rtsp
      protocol: TCP
    - port: 8555
      targetPort: 8555
      name: webrtc-tcp
      protocol: TCP
    - port: 8555
      targetPort: 8555
      name: webrtc-udp
      protocol: UDP
    - port: 1984
      targetPort: 1984
      name: http
      protocol: TCP
