---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-nodeport
spec:
  selector:
    {{ .Release.Name }}/app: frigate
  type: NodePort
  ports:
    - nodePort: 5000
      targetPort: 5000
      name: http
      protocol: TCP
    - nodePort: 8554
      targetPort: 8554
      name: rtsp
      protocol: TCP
    - nodePort: 8555
      targetPort: 8555
      name: webrtc-tcp
      protocol: TCP
    - nodePort: 8555
      targetPort: 8555
      name: webrtc-udp
      protocol: UDP