---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-nodeport
spec:
  selector:
    {{ .Release.Name }}/app: frigate
  type: NodePort
  ports:
    -   port: 5000
        nodePort: 30000
        targetPort: 5000
        name: http
        protocol: TCP
    -   port: 8554
        nodePort: 30554
        targetPort: 8554
        name: rtsp
        protocol: TCP
    -   port: 8555
        nodePort: 30555
        targetPort: 8555
        name: webrtc-tcp
        protocol: TCP
    -   port: 8555
        nodePort: 30555
        targetPort: 8555
        name: webrtc-udp
        protocol: UDP