---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    {{ .Release.Name }}/app: frigate
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      name: http
      protocol: TCP
    - port: 8554
      targetPort: 8554
      name: rtsp
      protocol: TCP
    - port: 8555
      targetPort: 8555
      name: webrtc-tcp
      protocol: TCP
    - port: 8555
      targetPort: 8555
      name: webrtc-udp
      protocol: UDP