{{ define "homelab.immich.deployment" }}
---
apiVersion: v1
kind: Service
metadata:
    name: immich-{{ .name }}
spec:
    type: ClusterIP
    ports:
        -   port: {{ .port }}
            targetPort: http
            protocol: TCP
            name: http
    selector:
        homelab/name: immich
        app.kubernetes.io/name: {{ .name }}
        app.kubernetes.io/instance: photos

{{- range $key, $val := .persistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-{{ $.name }}-{{ $key }}
spec:
  storageClassName: {{ $.global.nfs.storageClass }}
  accessModes: 
    {{- $val.accessModes | toYaml | nindent 4 }}
  resources:
    {{- $val.resources | toYaml | nindent 4 }}
{{ end -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: immich-{{ .name }}
spec:
    revisionHistoryLimit: 2
    replicas: {{ .replicas | int }}
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 0
    selector:
        matchLabels:
            homelab/name: immich
            app.kubernetes.io/name: {{ .name }}
            app.kubernetes.io/instance: photos
    template:
        metadata:
            labels:
                homelab/name: immich
                app.kubernetes.io/name: {{ .name }}
                app.kubernetes.io/instance: photos
        spec:
            containers:
                -   name: {{ .name }}
                    image: "{{.image}}:{{ .version }}"
                    imagePullPolicy: IfNotPresent
                    envFrom:
                        -   configMapRef: 
                                name: immich-shared-envs
                        -   secretRef: 
                                name: immich-shared-envs
                        -   secretRef:
                                name: immich-db
                    {{ if .env }}
                    env:
                        {{ .env | toYaml | nindent 24 }}
                    {{ end }}
                    ports:
                        -   name: http
                            containerPort: {{ .port }}
                            protocol: TCP
                    volumeMounts:
                        -   name: library
                            mountPath: "{{ .libraryMountPath }}"
                            subPath: "{{ .libraryMounSubtPath }}"
{{- range $key, $val := .persistence }}
                        -   name: {{ $key }}
                            mountPath: {{ $val.mountPath }}
{{ end }}
                    {{ if .command }}
                    command:
                        {{ .command | toYaml | nindent 24 }}
                    {{ end }}
                    {{ if .args }}
                    args:
                        {{ .args | toYaml | nindent 24 }}
                    {{ end }}
                    {{ if .livenessProbe }}
                    livenessProbe:
                        {{ .livenessProbe | toYaml | nindent 24 }}
                    {{ end }}
                    {{ if .readinessProbe }}
                    readinessProbe:
                        {{ .readinessProbe | toYaml | nindent 24 }}
                    {{ end }}
                    {{ if .startupProbe }}
                    startupProbe:
                        {{ .startupProbe | toYaml | nindent 24 }}
                    {{ end }}
            volumes:
                -   name: library
                    {{- .libraryPVC | toYaml | nindent 20 }}
{{- range $key, $val := .persistence }}
                -   name: {{ $key }}
                    persistentVolumeClaim:
                        claimName: immich-{{ $.name }}-{{ $key }}
{{ end }}

{{ end }}