---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "immich-db"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: chart-database
  target:
    name: "immich-db"
  data:
    - secretKey: "DB_USERNAME"
      remoteRef:
        key: "password.pg.immich"
        property: username

    - secretKey: "DB_PASSWORD"
      remoteRef:
        key: "password.pg.immich"
        property: password

    - secretKey: "DB_HOSTNAME"
      remoteRef:
        key: "password.pg.immich"
        property: host

    - secretKey: "DB_PORT"
      remoteRef:
        key: "password.pg.immich"
        property: host
