---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: immich-shared-envs
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: TYPESENSE_API_KEY
stringData:
    DB_DATABASE_NAME: immich