
image: homeassistant/home-assistant
tag: "2023.10"

persistence:
    config:
        claimName: ""

resources:
    requests:
        memory: "500Mi"
        cpu: "150m"
    limits:
        memory: "500Mi"
        cpu: "150m"
