nfs:
  shares:
    torrents: "/mnt/EightTerra/DownloadedTorrents"
    familyvideos: "/mnt/EightTerra/FamilyStorage/Video"
plex:
  repo: "plexinc/pms-docker"
  tag: "1.31.3.6868-28fc46b27"

linuxserverServices:
  transmission:
    repo: lscr.io/linuxserver/transmission
    tag: "4.0.2"
    ports:
      - port: 9091
        targetPort: 9091
        name: "web"
      - port: 51413
        targetPort: 51413
        name: "51413"
      - port: 51413
        targetPort: 51413
        protocol: UDP
        name: "51413-udp"
    podResources:
      limits:
        cpu: 1
        memory: "2Gi"
      requests:
        cpu: 800m
        memory: "500M"
    configVolumesResources:
      requests:
        storage: 10Gi
      limits:
        storage: 100Gi
  sonarr:
    repo: lscr.io/linuxserver/sonarr
    tag: "3.0.10"
    podResources:
      limits:
        cpu: 1
        memory: "2Gi"
      requests:
        cpu: 500m
        memory: "500M"
    configVolumesResources:
      requests:
        storage: 10Gi
      limits:
        storage: 100Gi
    ports:
      - port: 8989
        targetPort: 8989
        name: "web"
  radarr:
    repo: lscr.io/linuxserver/radarr
    tag: "4.3.2"
    podResources:
      limits:
        cpu: 1
        memory: "2Gi"
      requests:
        cpu: 500m
        memory: "500M"
    configVolumesResources:
      requests:
        storage: 10Gi
      limits:
        storage: 100Gi
    ports:
      - port: 7878
        targetPort: 7878
        name: "web"
  jackett:
    repo: lscr.io/linuxserver/jackett
    tag: "0.20.3772"
    envVars:
      AUTO_UPDATE: "true"
    podResources:
      limits:
        cpu: 1
        memory: "2Gi"
      requests:
        cpu: 500m
        memory: "500M"
    configVolumesResources:
      requests:
        storage: 10Gi
      limits:
        storage: 100Gi
    ports:
      - port: 9117
        targetPort: 9117
        name: "web"
  # qbittorrent:
  #   repo: lscr.io/linuxserver/qbittorrent
  #   tag: "4.5.2"
  #   envVars:
  #     AUTO_UPDATE: "true"
  #   podResources:
  #     limits:
  #       cpu: 2
  #       memory: "2Gi"
  #     requests:
  #       cpu: 1
  #       memory: "500M"
  #   configVolumesResources:
  #     requests:
  #       storage: 10Gi
  #     limits:
  #       storage: 100Gi
  #   ports:
  #     - port: 8080
  #       targetPort: 8080
  #       name: "web"
  #     - port: 6881
  #       targetPort: 6881
  #       name: "6881"
  #     - port: 6881
  #       targetPort: 6881
  #       protocol: UDP
  #       name: "6881-udp"
