{{ if .Values.smtp_configs }}
---
apiVersion: v1
kind: Secret
metadata:
  name:  "postfix-smtp-env"
type: Opaque
data:
  SERVER_HOSTNAME: "{{ .Values.global.domain | b64enc }}"
{{ range $k, $v := .Values.smtp_configs }}
  {{ $k }}: "{{ $v | b64enc }}"
{{ end }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "postfix-smtp"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secrets
  target:
    name: "postfix-smtp-env"
    creationPolicy: Merge
  data:
    - secretKey: "SMTP_PASSWORD"
      remoteRef:
        key: "smtp"
        property: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  labels:
    app: postfix
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
      annotations:
        postfix/env-checksum: "{{ .Values.smtp_configs | toJson | sha256sum }}"
    spec:
      containers:
        - image: juanluisbaptiste/postfix:alpine
          name: postfix
          resources:
            requests:
              cpu: "20m"
              memory: "55M"
            limits:
              cpu: "20m"
              memory: "55M"
          envFrom:
            - secretRef:
                name: postfix-smtp-env
          ports:
            - containerPort: 25
              name: smtp
      restartPolicy: Always
      imagePullPolicy: IfNotPresent
---
kind: Service
apiVersion: v1
metadata:
  name:  postfix
spec:
  selector:
    app:  postfix
  type:  ClusterIP
  ports:
  - name: smtp
    port:  25
    targetPort:  25
{{ end }}