global:
  deployment: prod
  domain: "home.sosnovsky.ca"
  tls:
    enabled: true
    issuer: "letsencrypt"
    acmeServer: "https://acme-v02.api.letsencrypt.org/directory"
    skipTLSVerify: true
  nfs:
    server: "192.168.8.107"
    share: "/mnt/EightTerra/k3s-cluster"
    additionalShares:
      torrents: "/mnt/EightTerra/DownloadedTorrents"
      familyvideos: "/mnt/EightTerra/FamilyStorage/Video"
  mqtt:
    username: k3s
    password: fZ!HauNB9%

secrets:
  ingresses:
    secrets:
      cloudflare:
        name: "cloudflare-apitoken"
