gitops:
  repo: ""
  commit: ""

apps:
  ingresses: {}
  db-users:
    namespace: chart-database
    values: |-
      postgresSecret: "{{ .Values.secrets.database.secrets.dbmain.name }}"

global:
  email: "ariel@sosnovsky.ca"
  timezone: America/Toronto
  domain: ""
  tls:
    enabled: false
    issuer: ""
    acmeServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
    skipTLSVerify: "false"
  nfs:
    storageClass: "nfs-generic"
    server: "changme"
    share: "changeme"

infrastructureCharts:
  cert-manager:
    repoURL: "https://charts.jetstack.io"
    targetRevision: "1.10.2"
    values: |-
      installCRDs: true
  external-secrets:
    repoURL: "https://charts.external-secrets.io"
    targetRevision: "0.7.2"
    values: |-
      installCRDs: true
  nfs-generic-storageclass:
    chart: nfs-subdir-external-provisioner
    repoURL: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/"
    targetRevision: "v4.0.2"
    values: |-
      storageClass:
          name: "{{ .Values.global.nfs.storageClass }}"
      nfs:
          server: "{{ .Values.global.nfs.server }}"
          path: "{{ .Values.global.nfs.share }}"
  kubernetes-secret-generator:
    repoURL: "https://helm.mittwald.de"
    targetRevision: "v3.4.0"
  database:
    chart: postgresql
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: "12.1.8"
    values: |-
      fullnameOverride: "postgres"
      image:
          tag: 15.1.0-debian-11-r19
          repository: bitnami/postgresql
          pullPolicy: IfNotPresent
      auth:
          secretKeys:
              adminPasswordKey: password
          existingSecret: "{{ .Values.secrets.database.secrets.dbmain.name }}"
      architecture: standalone
      postgresqlDataDir: /bitnami/postgresql/data
      primary:
          persistence:
              enabled: true
              mountPath: /bitnami/postgresql
              storageClass: "{{ .Values.global.nfs.storageClass }}"
              existingClaim: "{{ .Values.storage.database.name }}"
              accessModes:
                  - ReadWriteMany
      readReplicas:
          replicaCount: 0

secrets:
  database:
    namespace: chart-database
    secrets:
      dbmain:
        name: "pg.password"
storage:
  database:
    name: primary-database
    namespace: chart-database
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 8Gi
