gitops:
  repo: ""
  commit: ""

global:
  email: "ariel@sosnovsky.ca"
  timezone: America/Toronto
  domain: "changeme"
  tls:
    enabled: false
    issuer: ""
    acmeServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
    skipTLSVerify: "false"
  nfs:
    storageClass: "nfs-generic"
    server: "changme"
    share: "changeme"
    additionalShares:
      torrents: "changeme"
      familyvideos: "changeme"
  smtp:
    email: "ariel.sosnovsky@gmail.com"

videohosting:
  linuxserverServices:
    transmission:
      ports:
        tcp:
          web: 9091
          51413: 51413
        udp:
          51413: 51413
    sonarr:
      ports:
        tcp:
          web: 8989
    radarr:
      ports:
        tcp:
          web: 7878
    jackett:
      ports:
        tcp:
          web: 9117
    qbittorrent:
      ports:
        tcp:
          web: 8080
          6881: 6881
        udp:
          6881: 6881

apps:
  videohosting:
    values: |-
      {{ .Values.videohosting | toYaml }}
  nextcloud:
    values: |-
      nextcloud:
        nextcloud:
          host: "nextcloud.{{ .Values.global.domain }}"
        externalDatabase:
          host: postgres.chart-database.svc.cluster.local
        persistence:
          storageClass: {{ .Values.global.nfs.storageClass }}
          existingClaim: {{ .Values.storage.nextcloudConfig.name }}
          nextcloudData:
            storageClass: {{ .Values.global.nfs.storageClass }}
            existingClaim: {{ .Values.storage.nextcloudData.name }}
        configs:
          authelia.config.php: |-
            <?php
              $CONFIG = array (
                  'allow_user_to_change_display_name' => false,
                  'lost_password_link' => 'disabled',
                  'oidc_login_provider_url' => 'https://auth.core.{{ .Values.global.domain }}',
                  'oidc_login_client_id' => 'nextcloud',
                  'oidc_login_client_secret' => 'xjW7ByDrY0IpGo6XC5o6eQEUGagjkK6hULfbtADO5GV-ugHiG1ri1FRvkfL.-sacdHWyqZyO',
                  'oidc_login_auto_redirect' => false,
                  'oidc_login_end_session_redirect' => false,
                  'oidc_login_button_text' => 'Log in with Authelia',
                  'oidc_login_hide_password_form' => false,
                  'oidc_login_use_id_token' => true,
                  'oidc_login_attributes' => array (
                      'id' => 'preferred_username',
                      'name' => 'name',
                      'mail' => 'email',
                      'groups' => 'groups',
                  ),
                  'oidc_login_default_group' => 'oidc',
                  'oidc_login_use_external_storage' => false,
                  'oidc_login_scope' => 'openid profile email groups',
                  'oidc_login_proxy_ldap' => false,
                  'oidc_login_disable_registration' => true,
                  'oidc_login_redir_fallback' => false,
                  'oidc_login_alt_login_page' => 'assets/login.php',
                  'oidc_login_tls_verify' => true,
                  'oidc_create_groups' => false,
                  'oidc_login_webdav_enabled' => false,
                  'oidc_login_password_authentication' => false,
                  'oidc_login_public_key_caching_time' => 86400,
                  'oidc_login_min_time_between_jwks_requests' => 10,
                  'oidc_login_well_known_caching_time' => 86400,
                  'oidc_login_update_avatar' => false,
              );

  ingresses:
    values: |-
      services:
        - prefix: "argocd.core"
          service: "argocd-server"
          namespace: "argocd"
        - prefix: "monitoring.core"
          service: prometheus-kube-prometheus-prometheus
          namespace: chart-prometheus
          middleware: "apps-ingresses-chain-authelia"
          port: 9090
        - prefix: "alerts.core"
          service: prometheus-kube-prometheus-alertmanager
          namespace: chart-prometheus
          middleware: "apps-ingresses-chain-authelia"
          port: 9093
        - prefix: "grafana.core"
          service: prometheus-grafana
          namespace: chart-prometheus
          middleware: "apps-ingresses-chain-authelia"
        - prefix: "demo"
          service: "dummy-app"
          namespace: "apps-ingresses"
        - prefix: "nextcloud"
          service: "nextcloud"
          namespace: "apps-nextcloud"
          port: 8080
          middleware: "apps-nextcloud-nextcloud"
        - prefix: "plex"
          service: "plex"
          namespace: "apps-videohosting"
          port: 32400
        {{- range $k, $v := .Values.videohosting.linuxserverServices }}
        - prefix: "{{ $k }}.vh"
          service: "{{ $k }}"
          namespace: "apps-videohosting"
          port: {{ $v.ports.tcp.web }}
          middleware: "apps-ingresses-chain-authelia"
        {{- end }}

  db-users:
    namespace: chart-database
    values: |-
      postgresSecret: "{{ .Values.secrets.database.secrets.dbmain.name }}"

  postfix:
    namespace: email
    values: |-
      smtp_configs:
        SMTP_SERVER: "smtp.gmail.com"
        SMTP_PORT: "587"
        SMTP_USERNAME: "{{.Values.global.smtp.email}}"
      smtp_password_secret: {{ .Values.secrets.smtp.secrets.smtp.name }}
      smtp_password_secret_key: password

  authelia:
    valuesFile: authelia.yaml

  kerberos:
    values: |-
      common:
        storageClaimName: {{ .Values.storage.kerberos.name }}

infrastructureCharts:
  cert-manager:
    repoURL: "https://charts.jetstack.io"
    targetRevision: "1.10.2"
    values: |-
      installCRDs: true
  external-secrets:
    repoURL: "https://charts.external-secrets.io"
    targetRevision: "0.7.2"
    values: |-
      installCRDs: true
  nfs-generic-storageclass:
    chart: nfs-subdir-external-provisioner
    repoURL: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/"
    targetRevision: "v4.0.2"
    values: |-
      storageClass:
          name: "{{ .Values.global.nfs.storageClass }}"
      nfs:
          server: "{{ .Values.global.nfs.server }}"
          path: "{{ .Values.global.nfs.share }}"
  kubernetes-secret-generator:
    repoURL: "https://helm.mittwald.de"
    targetRevision: "v3.4.0"
  database:
    chart: postgresql
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: "12.1.8"
    valuesFile: database.yaml
  prometheus:
    chart: kube-prometheus-stack
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: "45.10.1"
    valuesFile: prometheus.yaml
secrets:
  database:
    namespace: chart-database
    secrets:
      dbmain:
        name: "pg.password"
  smtp:
    namespace: email
    secrets:
      smtp:
        name: "smtp.creds"
        data: |-
          username: "{{.Values.global.smtp.email | b64enc }}"

storage:
  database:
    name: primary-database
    namespace: chart-database
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 8Gi
  authelia:
    name: authelia
    namespace: apps-authelia
    accessModes:
      - ReadWriteMany
    resources:
      limits:
        storage: 5Gi
      requests:
        storage: 5Gi
  nextcloudData:
    name: nextcloud-data
    namespace: apps-nextcloud
    accessModes:
      - ReadWriteMany
    resources:
      limits:
        storage: 100Gi
      requests:
        storage: 10Gi
  nextcloudConfig:
    name: nextcloud-config
    namespace: apps-nextcloud
    accessModes:
      - ReadWriteMany
    resources:
      limits:
        storage: 100Gi
      requests:
        storage: 10Gi
  kerberos:
    name: kerberos
    namespace: apps-kerberos
    accessModes:
      - ReadWriteMany
    resources:
      limits:
        storage: 100Gi
      requests:
        storage: 10Gi
