global:
  deployment: prod
  domain: "home.sosnovsky.ca"
  tls:
    useWildCard: true
    enabled: true
    issuer: "letsencrypt"
    acmeServer: "https://acme-v02.api.letsencrypt.org/directory"
    skipTLSVerify: true
  nfs:
    server: "192.168.8.107"
    share: "/mnt/EightTerra/k3s-cluster"
    additionalShares:
      torrents: "/mnt/EightTerra/DownloadedTorrents"
      familyvideos: "/mnt/EightTerra/FamilyStorage/Video"
      familyphotos: "/mnt/EightTerra/FamilyStorage/Pictures"
  mqtt:
    username: k3s
    password: fZ!HauNB9%

secrets:
  ingresses:
    secrets:
      cloudflare:
        name: "cloudflare-apitoken"

infrastructureCharts:
  amd-gpu:
    repoURL: "https://radeonopencompute.github.io/k8s-device-plugin/"
    targetRevision: "0.10.0"
    values: |-
      namespace: chart-amd-gpu
      labeller:
        enabled: true
  node-feature-discovery:
    repoURL: "https://kubernetes-sigs.github.io/node-feature-discovery/charts"
    targetRevision: "0.10.0"
    values: |-
      namespace: chart-node-feature-discovery