gitops:
  repo: ""
  commit: ""

global:
  email: "ariel@sosnovsky.ca"
  timezone: America/Toronto
  domain: "changeme"
  tls:
    enabled: false
    issuer: ""
    acmeServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
    skipTLSVerify: "false"
  nfs:
    storageClass: "nfs-generic"
    server: "changme"
    share: "changeme"
    additionalShares:
      torrents: "changeme"
      familyvideos: "changeme"
      familyphotos: "changeme"
  smtp:
    email: "ariel.sosnovsky@gmail.com"
  mqtt:
    port: 1883
    host: 192.168.0.23

videohosting:
  linuxserverServices:
    transmission:
      ports:
        tcp:
          web: 9091
          51413: 51413
        udp:
          51413: 51413
    sonarr:
      ports:
        tcp:
          web: 8989
    radarr:
      ports:
        tcp:
          web: 7878
    jackett:
      ports:
        tcp:
          web: 9117
    qbittorrent:
      ports:
        tcp:
          web: 8080
          6881: 6881
        udp:
          6881: 6881

apps:
  videohosting:
    values: |-
      {{ .Values.videohosting | toYaml }}

  nextcloud:
    valuesFile: nextcloud.yaml

  ingresses:
    valuesFile: ingresses.yaml

  db-users:
    namespace: chart-database
    values: |-
      postgresSecret: "{{ .Values.secrets.database.secrets.dbmain.name }}"

  postfix:
    namespace: email
    values: |-
      smtp_configs:
        SMTP_SERVER: "smtp.gmail.com"
        SMTP_PORT: "587"
        SMTP_USERNAME: "{{.Values.global.smtp.email}}"
      smtp_password_secret: {{ .Values.secrets.smtp.secrets.smtp.name }}
      smtp_password_secret_key: password

  frigate:
    values: |-
      persistence:
        media_path:
            enabled: true
            claimName: {{ .Values.storage.frigateMedia.name }}
        conf_path:
            enabled: true
            claimName: {{ .Values.storage.frigateConf.name }}

infrastructureCharts:
  cert-manager:
    repoURL: "https://charts.jetstack.io"
    targetRevision: "1.10.2"
    values: |-
      installCRDs: true
  rancher:
    repoURL: "https://releases.rancher.com/server-charts/latest"
    targetRevision: "2.7.5-rc1"
    values: |-
      hostname: "rancher.core.{{ .Values.global.domain }}"
      ingress: 
          enabled: false
      tls: none
  external-secrets:
    repoURL: "https://charts.external-secrets.io"
    targetRevision: "0.7.2"
    values: |-
      installCRDs: true
  nfs-generic-storageclass:
    chart: nfs-subdir-external-provisioner
    repoURL: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/"
    targetRevision: "v4.0.2"
    values: |-
      storageClass:
          name: "{{ .Values.global.nfs.storageClass }}"
      nfs:
          server: "{{ .Values.global.nfs.server }}"
          path: "{{ .Values.global.nfs.share }}"
  kubernetes-secret-generator:
    repoURL: "https://helm.mittwald.de"
    targetRevision: "v3.4.0"
  database:
    chart: postgresql
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: "12.1.8"
    valuesFile: database.yaml
  prometheus:
    chart: kube-prometheus-stack
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: "45.10.1"
    valuesFile: prometheus.yaml
  authentik:
    repoURL: https://charts.goauthentik.io
    targetRevision: "2023.8.3"
    valuesFile: authentik.yaml

secrets:
  ingresses:
    enableClusterStore: true
    namespace: apps-ingresses
    secrets: {}
  database:
    enableClusterStore: true
    namespace: chart-database
    secrets:
      dbmain:
        name: "pg.password"
  smtp:
    enableClusterStore: true
    namespace: email
    secrets:
      smtp:
        name: "smtp.creds"
        data: |-
          username: "{{.Values.global.smtp.email | b64enc }}"
  prometheus:
    namespace: chart-prometheus
    configmaps:
      auth:
        name: authentick-config-envs
  authentik:
    namespace: chart-authentik
    secrets:
      env:
        name: "authentik-env"
        autogenerated:
          - AUTHENTIK_SECRET_KEY
        data: |-
          AUTHENTIK_DEFAULT_USER_CHANGE_USERNAME: {{ "False" | b64enc }}
        external:
          AUTHENTIK_POSTGRESQL__PASSWORD:
            store: chart-database
            secretName: "password.pg.authentik"
            secretKey: "password"
storage:
  database:
    name: primary-database
    namespace: chart-database
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 8Gi
  nextcloudData:
    name: nextcloud-data
    namespace: apps-nextcloud
    accessModes:
      - ReadWriteMany
    resources:
      limits:
        storage: 100Gi
      requests:
        storage: 10Gi
  nextcloudConfig:
    name: nextcloud-config
    namespace: apps-nextcloud
    accessModes:
      - ReadWriteMany
    resources:
      limits:
        storage: 100Gi
      requests:
        storage: 10Gi
  nextcloudRedisMaster:
    name: redis-master
    namespace: apps-nextcloud
    accessModes:
      - ReadWriteMany
    resources:
      limits:
        storage: 20Gi
      requests:
        storage: 1Gi
  frigateMedia:
    name: frigate-media
    namespace: apps-frigate
    accessModes:
      - ReadWriteMany
    resources:
      limits:
        storage: 100Gi
      requests:
        storage: 10Gi
  frigateConf:
    name: frigate-conf
    namespace: apps-frigate
    accessModes:
      - ReadWriteMany
    resources:
      limits:
        storage: 1Gi
      requests:
        storage: 100Mi
