authelia:
  domain: "sosnovsky.ca"
  default_redirection_url: "home.sosnovsky.ca"
  notifier:
    disable_startup_check: false
    smtp:
      enabled: true
      enabledSecret: true
      username: arielsosnovsky@gmail.com
      sender: authellia@sosnovsky.ca
      host: smtp.gmail.com
      port: 587
    filesystem:
      enabled: false
