---
apiVersion: v1
kind: Secret
metadata:
  name: "authentik-env"
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: AUTHENTIK_SECRET_KEY
data:
  _placeholder: ""
type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "authentik-env-db"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: database
  target:
    name: "authentik-env"
    creationPolicy: Merge
  data:
    - secretKey: "AUTHENTIK_POSTGRESQL__PASSWORD"
      remoteRef:
        key: "password.pg.authentik"
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "authentik-env-smtp"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secrets
  target:
    name: "authentik-env"
    creationPolicy: Merge
  data:
    - secretKey: "AUTHENTIK_EMAIL__PASSWORD"
      remoteRef:
        key: "smtp"
        property: password
