---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: database
spec:
  provider:
    kubernetes:
      remoteNamespace: database
      caProvider:
        type: ConfigMap
        name: kube-root-ca.crt
        key: ca.crt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.nextcloud.externalDatabase.existingSecret.secretName }}"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: database
  target:
    name: "{{ .Values.nextcloud.externalDatabase.existingSecret.secretName }}" # name of the k8s Secret to be created
  data:
    - secretKey: username
      remoteRef:
        key: "{{ .Values.nextcloud.externalDatabase.existingSecret.secretName }}"
        property: username

    - secretKey: password
      remoteRef:
        key: "{{ .Values.nextcloud.externalDatabase.existingSecret.secretName }}"
        property: password
