---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.nextcloud.externalRedis.existingSecret }}"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: redis
  target:
    name: "{{ .Values.nextcloud.externalRedis.existingSecret }}" # name of the k8s Secret to be created
  data:
    - secretKey: "{{ .Values.nextcloud.externalRedis.auth.existingSecretPasswordKey }}"
      remoteRef:
        key: "{{ .Values.nextcloud.externalRedis.existingSecret }}"
        property: password
