---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Values.nextcloud.nextcloud.existingSecret.secretName }}"
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: "{{ .Values.nextcloud.nextcloud.existingSecret.usernameKey }},{{ .Values.nextcloud.nextcloud.existingSecret.passwordKey }}"
data:
  empty: ""
