---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: database
spec:
  provider:
    kubernetes:
      remoteNamespace: "{{ .Release.Namespace }}"
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: "{{ .Release.Namespace }}"
      auth:
        serviceAccount:
          name: "{{ .Release.Namespace }}"
          namespace: "{{ .Release.Namespace }}"
