{{ if .Values.flags.enableNodePort }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-nodeport
spec:
  selector:
    {{ .Release.Name }}/app: scrypted
  type: NodePort
  ports:
      - port: 443
        nodePort: 30001
        targetPort: 10443
        name: https
        protocol: TCP
    -   port: 80
        nodePort: 30002
        targetPort: 11080
        name: http
        protocol: TCP
{{ end }}