---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    {{ .Release.Name }}/app: scrypted
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 10443
      name: http
      protocol: TCP