---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-terraform
  namespace: {{ .Release.Namespace }}
data:
    run.sh: {{ include "pg-users.entry" . | b64enc }}
    main.tf: {{ include "pg-users.terraform" . | b64enc }}
    users.tfvars: {{ (print "db_users = " ( .Values.users | toJson  )) | b64enc }}
