---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-users
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      serviceAccount: {{ .Release.Name }}
      serviceAccountName: {{ .Release.Name }}
      volumes:
        - name: tffiles
          secret:
            secretName: {{ .Release.Name }}-terraform
      containers:
        - name: base
          image: hashicorp/terraform:{{ .Chart.AppVersion }}
          command: 
            - sh 
            - /app/run.sh
          volumeMounts:
            - mountPath: /app
              name: tffiles
          env:
            - name: TF_LOG_PATH
              value: /tmp/terraform.log
            - name: TF_INPUT
              value: "0"
            - name: TF_DATA_DIR
              value: /tmp/.terraform
            - name: TF_IN_AUTOMATION
              value: "1"
            - name: TF_VAR_db_host
              value: "{{ .Values.postgres.host }}"
            - name: TF_VAR_db_username
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgres.secretName }}"
                  key: "{{ .Values.postgres.secretUserKey }}"
            - name: TF_VAR_db_password
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgres.secretName }}"
                  key: "{{ .Values.postgres.secretPasswordKey }}"
      restartPolicy: Never
  backoffLimit: 4
