---
apiVersion: v1
kind: Namespace
metadata:
    name: homepage
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "homepage"
  namespace: {{ .Values.ns.argocd }}
spec:
    project: main
    source:
        path: 'charts/homepage'
        repoURL: "git@github.com:asosnovsky/helm-charts.git"
        targetRevision: main
        helm:
            values: |-
                allowedHosts: "home.k3s.local" 
    destination:
        namespace: "homepage"
        server: https://kubernetes.default.svc
    syncPolicy:
        automated:
            prune: true
            selfHeal: true

---
{{ include "homelab.ingress" (dict 
    "global" $.Values.global
    "prefix" "home"
    "service" "homepage"
    "namespace" "homepage"
    "disableExternalIngress" true
) }}
