{{  if .Values.global.dns.tls.enabled  }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: {{ .Values.global.dns.tls.issuer }}
spec:
    acme:
        server: {{ .Values.global.dns.tls.acmeServer }}
        skipTLSVerify: {{ .Values.global.dns.tls.skipTLSVerify }}
        email: {{ .Values.global.email }}
        privateKeySecretRef:
            name: {{ .Values.global.dns.tls.issuer }}
        solvers:
            -   http01:
                    ingress:
                        class: traefik

{{ if .Values.cloudflare.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare
spec:
  acme:
    server: {{ .Values.global.dns.tls.acmeServer }}
    skipTLSVerify: {{ .Values.global.dns.tls.skipTLSVerify }}
    email: {{ .Values.global.email }}
    privateKeySecretRef:
        name: cloudflare
    solvers:
        -   dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: {{ .Values.cloudflare.tokenSecretName }}
                        key: {{ .Values.cloudflare.tokenSecretKey }}

{{ range $prefix := .Values.cloudflare.certificateRootDomains }}       
# <.{{$prefix}}.*>
{{include "homelab.cert" (merge (dict "prefix" $prefix) $.Values.global.dns.primary)}}
{{include "homelab.cert" (merge (dict "prefix" $prefix) $.Values.global.dns.secondary)}}
# </.{{$prefix}}.*>
{{ end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudflare.{{ $.Values.global.dns.primary.domain }}
spec:
  secretName: cloudflare.{{ $.Values.global.dns.primary.domain }}
  issuerRef:
    name: cloudflare
    kind: Issuer
  commonName: '{{ $.Values.global.dns.primary.domain }}'
  dnsNames:
    -   "{{ $.Values.global.dns.primary.domain }}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudflare.{{ $.Values.global.dns.secondary.domain }}
spec:
  secretName: cloudflare.{{ $.Values.global.dns.secondary.domain }}
  issuerRef:
    name: cloudflare
    kind: Issuer
  commonName: '{{ $.Values.global.dns.secondary.domain }}'
  dnsNames:
    -   "{{ $.Values.global.dns.secondary.domain }}"
{{ end }}
{{ end }}