{{  if .Values.global.tls.enabled  }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
    name: {{ .Values.global.tls.issuer }}
spec:
    acme:
        server: {{ .Values.acmeServer }}
        skipTLSVerify: {{ .Values.skipTLSVerify }}
        email: {{ .Values.global.email }}
        privateKeySecretRef:
            name: {{ .Values.global.tls.issuer }}
        solvers:
        - http01:
            ingress:
                class: traefik
{{ end }}