---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nextcloud
  namespace: app-nextcloud
spec:
  chain:
    middlewares:
      - name: https-only
      - name: strict-transport
      - name: well-known

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: well-known
  namespace: app-nextcloud
spec:
  redirectRegex:
    permanent: true
    regex: "https://(.*)/.well-known/(?:card|cal)dav"
    replacement: "https://${1}/remote.php/dav"

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-only
  namespace: app-nextcloud
spec:
  redirectScheme:
    scheme: https

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strict-transport
spec:
  headers:
    customRequestHeaders:
      "Strict-Transport-Security": "max-age=15552000; includeSubDomains"
    customResponseHeaders:
      "Strict-Transport-Security": "max-age=15552000; includeSubDomains"
