---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nextcloud
  namespace: app-nextcloud
spec:
  chain:
    middlewares:
      - name: https-redirect
      - name: well-known
      - name: strict-transport

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: well-known
  namespace: app-nextcloud
spec:
  redirectRegex:
    permanent: true
    regex: "https://(.*)/.well-known/(?:card|cal)dav"
    replacement: "https://${1}/remote.php/dav"

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: app-nextcloud
spec:
  redirectScheme:
    scheme: https

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strict-transport
  namespace: app-nextcloud
spec:
  headers:
    hostsProxyHeaders:
      - "X-Forwarded-Host"
    referrerPolicy: "same-origin"
    stsSeconds: 15552000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
