---
apiVersion: v1
kind: Secret
metadata:
  name: "hashicorp-vault-login"
  namespace: "hashicorp-vault"
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
type: kubernetes.io/basic-auth
data:
  username: dXNlcg== # username: user
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: login
  namespace: "hashicorp-vault"
spec:
  basicAuth:
    secret: hashicorp-vault-login
