---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "transmission"
  namespace: {{ .Values.ns.argocd }}
spec:
    project: main
    source:
        path: 'charts/transmission'
        repoURL: "git@github.com:asosnovsky/helm-charts.git"
        targetRevision: main
        helm:
            values: |-
                gluetun:
                    envFrom:
                        - secretRef:
                            name: vpn-creds
    destination:
        namespace: {{ .Release.Namespace }}
        server: https://kubernetes.default.svc
    syncPolicy:
        automated:
            prune: true
            selfHeal: true