# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: "{{ $name }}"
#   namespace: {{ $.Values.ns.argocd }}
# spec:
#     project: main
#     source:
#         path: 'charts/compose-app'
#         repoURL: {{ $.Values.repo }}
#         targetRevision: {{ $.Values.revision }}
#         helm:
#             values: |-
#                 global:
#                     {{ $.Values.global | toYaml | nindent 20 }}
#                 {{ $data | toYaml | nindent 16 }}
#     destination:
#         namespace: {{ .Release.Namespace }}
#         server: https://kubernetes.default.svc
#     syncPolicy:
#         syncOptions:
#             - CreateNamespace=true
#         automation:
#             prune: true
#             selfHeal: true