---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "transmission"
  namespace: {{ .Values.ns.argocd }}
spec:
    project: main
    source:
        path: 'charts/transmission'
        repoURL: "git@github.com:asosnovsky/helm-charts.git"
        targetRevision: main
        helm:
            values: |-
                gluetun:
                    envFrom:
                        - secretRef:
                            name: vpn-credentials
                volumes:
                    -   name: "torrents"
                        nfs:
                            server: tnas1.lab.internal
                            path: /mnt/EightTerra/DownloadedTorrents
                    -   name: "config"
                        persistentVolumeClaim:
                            claimName: "transmission-config"
                transmission:
                    volumeMounts:
                        -   name: torrents
                            mountPath: /torrents
                        -   name: config
                            mountPath: /config
    destination:
        namespace: {{ .Release.Namespace }}
        server: https://kubernetes.default.svc
    syncPolicy:
        automated:
            prune: true
            selfHeal: true