---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: transmission-config
spec:
    accessModes:
        - "ReadWriteOnce"
    resources:
        requests:
            storage: "100Mi"
    storageClassName: {{ .Values.global.nfs.storageClassName }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent-config
spec:
    accessModes:
        - "ReadWriteOnce"
    resources:
        requests:
            storage: "100Mi"
    storageClassName: {{ .Values.global.nfs.storageClassName }}