global:
    dns:
        internalPrefix: "k3s.internal"
        primary:
            domain: "internal"
            root: "k3s"
        secondary:
            domain: "local"
            root: "k3s"
        tls:
            enabled: false

reverseProxy: {}
services: []
tailScaleServices: []
ns:
    argocd: plugin-argo-cd
