reverseProxy:
    castle:
        ip: "10.0.12.1"
        port: "80"
        overrides:
            icon: http://10.0.12.1:80/static/icons/favicon.ico
    jellyfin:
        ip: 10.0.10.5
        port: 8096
        overrides:
            prefix: "jellyfin"
            group: "Video Hosting"
    scrypted:
        ip: 10.0.10.7
        port: 11080
        useTailscale: true
        disableIngress: true
        overrides:
            group: "Cameras"
services:
    -   prefix: "demo"
        service: "dummy-app"
        namespace: "dummy"
        # middleware: "apps-ingresses-forwardauth-authentik"
        group: "Demo"
    -   prefix: "auth"
        service: "authelia"
        namespace: "authelia"
        group: "Admin"
    -   prefix: "torrent"
        service: "transmission"
        namespace: "torrents"
        group: "Torrenting"
        disableExternalIngress: true
        port: 9091
    -   prefix: "lidarr"
        service: "lidarr"
        namespace: "comap-arrs"
        group: "Torrenting"
        disableExternalIngress: true
    -   prefix: "radarr"
        service: "radarr"
        namespace: "comap-arrs"
        group: "Torrenting"
        disableExternalIngress: true
    -   prefix: "sonarr"
        service: "sonarr"
        namespace: "comap-arrs"
        group: "Torrenting"
        disableExternalIngress: true
    -   prefix: "prowlarr"
        service: "prowlarr"
        namespace: "comap-arrs"
        group: "Torrenting"
        disableExternalIngress: true
    -   prefix: "nzbget"
        service: "nzbget"
        namespace: "comap-arrs"
        group: "Torrenting"
        disableExternalIngress: true


tailScaleServices:
    -   name: "argocd"
        namespace: plugin-argo-cd
        selector:
            "app.kubernetes.io/instance" : "argo-cd"
            "app.kubernetes.io/name" : "argocd-server"
        port: 8080
