apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      homelab/app: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        homelab/app: "{{ .Release.Name }}"
    spec:
      affinity:
        {{- .Values.affinity | toYaml | nindent 12}}
      volumes:
        -   name: config
            persistentVolumeClaim:
              claimName: {{ .Values.persistence.config.claimName }}
      containers:
        -   name: main
            imagePullPolicy: "IfNotPresent"
            securityContext:
              privileged: true
            image: "{{ .Values.image }}:{{ .Values.tag | default .Chart.AppVersion }}"
            resources: 
              {{- .Values.resources | toYaml | nindent 14}}
            env:
              -   name: TZ
                  value: "{{ .Values.global.timezone }}"
            ports:
              -   containerPort: 8123
                  name: http
            volumeMounts:
              -   name: config
                  mountPath: /config
                  
