{{  if .Values.global.tls.enabled  }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: {{ .Values.global.tls.issuer }}
spec:
    acme:
        server: {{ .Values.global.tls.acmeServer }}
        skipTLSVerify: {{ .Values.global.tls.skipTLSVerify }}
        email: {{ .Values.global.email }}
        privateKeySecretRef:
            name: {{ .Values.global.tls.issuer }}
        solvers:
            -   http01:
                    ingress:
                        class: traefik

{{ if .Values.cloudflare.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare
spec:
  acme:
    server: {{ .Values.global.tls.acmeServer }}
    skipTLSVerify: {{ .Values.global.tls.skipTLSVerify }}
    email: {{ .Values.global.email }}
    privateKeySecretRef:
        name: cloudflare
    solvers:
        -   dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: {{ .Values.cloudflare.tokenSecretName }}
                        key: {{ .Values.cloudflare.tokenSecretKey }}
{{ range $prefix := .Values.cloudflare.certificateRootDomains }}       
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudflare-wildcard{{$prefix}}.{{ $.Values.global.rootSubDomain }}.{{ $.Values.global.domain }}
spec:
  secretName: cloudflare-wildcard{{$prefix}}.{{ $.Values.global.rootSubDomain }}.{{ $.Values.global.domain }}
  issuerRef:
    name: cloudflare
    kind: Issuer
  commonName: '*{{$prefix}}.{{ $.Values.global.rootSubDomain }}.{{ $.Values.global.domain }}'
  dnsNames:
    -   "*{{$prefix}}.{{ $.Values.global.rootSubDomain }}.{{ $.Values.global.domain }}"
{{ end }}
{{ end }}
{{ end }}