{{ range $prefix, $data := .Values.reverseProxy }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: "reverse-proxy-{{$prefix}}"
subsets:
- addresses:
  - ip: "{{ $data.ip }}"
  ports:
  - port: {{ $data.port | default 80 }}
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: "reverse-proxy-{{$prefix}}"
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{ $data.port | default 80 }}
{{ if (not $data.disableIngress) }}
{{- $ingressDef := (dict "service" (printf "reverse-proxy-%s" $prefix) "prefix" $prefix "global" $.Values.global "namespace" $.Release.Namespace "group" "reverse-proxies" ) -}}
{{- $ingressDef := (merge $ingressDef ($data.overrides | default (dict))) -}}

{{ include "homelab.ingress" $ingressDef}}

{{ end }}

{{ end }}