---
apiVersion: v1
kind: ConfigMap
metadata:
    name: db-envs
data:
    PGDATA: {{ .Values.database.pgdata }}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: db-cred
    annotations:
        secret-generator.v1.mittwald.de/autogenerate: "POSTGRES_PASSWORD"
stringData:
    POSTGRES_USER: "postgres"

---
kind: Service
apiVersion: v1
metadata:
  name: db
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: "pg"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  revisionHistoryLimit: 2
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    -   metadata:
          finalizers:
            - kubernetes.io/pvc-protection
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources: 
            requests:
              storage: 10Gi
            limits:
              storage: 100Gi
  template:
    metadata:
      labels:
        app: db
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            -   weight: 1
                preference:
                  matchExpressions:
                    -   key: homelab/capacity
                        operator: In
                        values:
                          - low
                          - med
      containers:
        - name: db
          image: "{{ .Values.database.repo }}:{{ .Values.database.tag }}"
          imagePullPolicy: "Always"
          envFrom:
            - configMapRef: 
                name: db-envs
            - secretRef: 
                name: db-cred
          ports:
            - containerPort: 5432
              name: db
          resources:
          {{- .Values.database.resources | toYaml | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.database.pgdata }}
          startupProbe:
            tcpSocket:
              port: db
            initialDelaySeconds: 10
            failureThreshold: 10
            timeoutSeconds: 30
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - '-e'
                - >
                  exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432

                  [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f
                  /bitnami/postgresql/.initialized ]
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5