global:
  timezone: changeme
  nfs:
    server: changeme
    additionalShares:
      torrents: "changeme"
      familyvideos: "changeme"
plex:
  repo: "plexinc/pms-docker"
  tag: "1.31.3.6868-28fc46b27"

linuxserverServices:
  sonarr:
    repo: lscr.io/linuxserver/sonarr
    tag: "latest"
    podResources:
      limits:
        cpu: 1
        memory: "2Gi"
      requests:
        cpu: 250m
        memory: "500M"
    configVolumesResources:
      requests:
        storage: 10Gi
      limits:
        storage: 100Gi
    ports:
      tcp:
        web: 8989
  radarr:
    repo: lscr.io/linuxserver/radarr
    tag: "latest"
    podResources:
      limits:
        cpu: 1
        memory: "2Gi"
      requests:
        cpu: 250m
        memory: "500M"
    configVolumesResources:
      requests:
        storage: 10Gi
      limits:
        storage: 100Gi
    ports:
      tcp:
        web: 7878
  jackett:
    repo: lscr.io/linuxserver/jackett
    tag: "latest"
    envVars:
      AUTO_UPDATE: "true"
    podResources:
      limits:
        cpu: 1
        memory: "2Gi"
      requests:
        cpu: 250m
        memory: "500M"
    configVolumesResources:
      requests:
        storage: 10Gi
      limits:
        storage: 100Gi
    ports:
      tcp:
        web: 9117
  qbittorrent:
    repo: linuxserver/qbittorrent
    tag: libtorrentv1
    ports:
      tcp:
        web: 8080
        6881: 6881
      udp:
        6881: 6881
    podResources:
      limits:
        cpu: 1
        memory: "4Gi"
      requests:
        cpu: 800m
        memory: "1.5Gi"
    configVolumesResources:
      requests:
        storage: 10Gi
      limits:
        storage: 100Gi
