global:
  timezone: changeme
  nfs:
    server: changeme
    additionalShares:
      torrents: "changeme"
      familyvideos: "changeme"
plex:
  repo: "plexinc/pms-docker"
  tag: "1.32.7"
  resources: 
    limits:
      cpu: 8
      memory: "10Gi"
    requests:
      cpu: 4
      memory: "4Gi"

arrs:
  sonarr:
    repo: lscr.io/linuxserver/sonarr
    tag: "4.0.0-develop"
    migrateDbFromSqllite: 
      enabled: false
      claimName: config-sonarr-0
    usePostgres: false
    podResources:
      limits:
        cpu: 2
        memory: "8Gi"
      requests:
        cpu: 250m
        memory: "500M"
    configVolumesResources:
      requests:
        storage: 10Gi
      limits:
        storage: 100Gi
    extraConfigXml: |-
      <InstanceName>Sosnovsky Sonarr</InstanceName>
      <AuthenticationMethod>External</AuthenticationMethod>
      <AuthenticationType>DisabledForLocalAddresses</AuthenticationType>
    
  radarr:
    repo: lscr.io/linuxserver/radarr
    tag: "latest"
    migrateDbFromSqllite: 
      enabled: false
      claimName: config-radarr-0
    usePostgres: true
    podResources:
      limits:
        cpu: 2
        memory: "8Gi"
      requests:
        cpu: 250m
        memory: "500M"
    configVolumesResources:
      requests:
        storage: 10Gi
      limits:
        storage: 100Gi
    extraConfigXml: |-
      <InstanceName>Sosnovsky Radarr</InstanceName>
      <AuthenticationMethod>External</AuthenticationMethod>
      <AuthenticationType>DisabledForLocalAddresses</AuthenticationType>

services:
  jackett:
    repo: lscr.io/linuxserver/jackett
    tag: "latest"
    envVars:
      AUTO_UPDATE: "true"
    podResources:
      limits:
        cpu: 500m
        memory: "1Gi"
      requests:
        cpu: 250m
        memory: "500M"
    health:
      readiness: "/health"
      liveness: "/health"
    configVolumesResources:
      requests:
        storage: 10Gi
      limits:
        storage: 100Gi
    ports:
      tcp:
        web: 9117
  qbittorrent:
    repo: linuxserver/qbittorrent
    tag: libtorrentv1
    ports:
      tcp:
        web: 8080
        6881: 6881
      udp:
        6881: 6881
    podResources:
      limits:
        cpu: 2
        memory: "8Gi"
      requests:
        cpu: 800m
        memory: "4Gi"
    health: {}
    configVolumesResources:
      requests:
        storage: 10Gi
      limits:
        storage: 100Gi
