global:
  timezone: changeme
  nfs:
    server: changeme
    additionalShares:
      torrents: "changeme"
      familyvideos: "changeme"
plex:
  repo: "plexinc/pms-docker"
  tag: "1.31.3.6868-28fc46b27"

linuxserverServices:
  # transmission:
  #   repo: lscr.io/linuxserver/transmission
  #   tag: "4.0.2"
  #   ports:
  #     tcp:
  #       web: 9091
  #       51413: 51413
  #     udp:
  #       51413: 51413
  #   podResources:
  #     limits:
  #       cpu: 1
  #       memory: "2Gi"
  #     requests:
  #       cpu: 800m
  #       memory: "500M"
  #   configVolumesResources:
  #     requests:
  #       storage: 10Gi
  #     limits:
  #       storage: 100Gi
  sonarr:
    repo: lscr.io/linuxserver/sonarr
    tag: "3.0.10"
    podResources:
      limits:
        cpu: 1
        memory: "2Gi"
      requests:
        cpu: 500m
        memory: "500M"
    configVolumesResources:
      requests:
        storage: 10Gi
      limits:
        storage: 100Gi
    ports:
      tcp:
        web: 8989
  radarr:
    repo: lscr.io/linuxserver/radarr
    tag: "latest"
    podResources:
      limits:
        cpu: 1
        memory: "2Gi"
      requests:
        cpu: 500m
        memory: "500M"
    configVolumesResources:
      requests:
        storage: 10Gi
      limits:
        storage: 100Gi
    ports:
      tcp:
        web: 7878
  jackett:
    repo: lscr.io/linuxserver/jackett
    tag: "0.20.3772"
    envVars:
      AUTO_UPDATE: "true"
    podResources:
      limits:
        cpu: 1
        memory: "2Gi"
      requests:
        cpu: 500m
        memory: "500M"
    configVolumesResources:
      requests:
        storage: 10Gi
      limits:
        storage: 100Gi
    ports:
      tcp:
        web: 9117
  qbittorrent:
    repo: linuxserver/qbittorrent
    tag: 4.5.2-libtorrentv1
    ports:
      tcp:
        web: 8080
        6881: 6881
      udp:
        6881: 6881
    podResources:
      limits:
        cpu: 1
        memory: "4Gi"
      requests:
        cpu: 800m
        memory: "1.5Gi"
    configVolumesResources:
      requests:
        storage: 10Gi
      limits:
        storage: 100Gi
