
services:
    jellyplex:
        envVars:
          USER_MAPPING: >-
            { \"ari\": \"arielso6\", \"vita\": \"vitakoren\" }
        LIBRARY_MAPPING: >- 
            { \"Shows\": \"TV Shows\" }
