reverseProxy: {}
services:
  - prefix: "argocd.core"
    service: "argocd-server"
    namespace: "argocd"
  - prefix: "nextcloud"
    service: "nextcloud"
    namespace: "app-nextcloud"
    port: 8080
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: app-nextcloud-nextcloud@kubernetescrd
  - prefix: "vault.core"
    service: "vault"
    namespace: "hashicorp-vault"
    port: 8200
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: hashicorp-vault-login@kubernetescrd
global: {}
acmeServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
skipTLSVerify: "false"
