reverseProxy: {}
services:
  - prefix: "argocd.core"
    service: "argocd-server"
    namespace: "argocd"
  - prefix: "demo"
    service: "dummy-app"
    namespace: "ingresses"
    middleware: "ingresses-forwardauth-authelia"
  - prefix: "nextcloud"
    service: "nextcloud"
    namespace: "app-nextcloud"
    port: 8080
    middleware: "app-nextcloud-nextcloud"
  - prefix: "authentik.core"
    service: "authentik"
    namespace: "authentik"
    port: 80
global: {}
acmeServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
skipTLSVerify: "false"
