reverseProxy: {}
services:
  - prefix: "argocd.core"
    service: "argocd-server"
    namespace: "argocd"
  - prefix: "demo"
    service: "dummy-app"
    namespace: "ingresses"
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: ingresses-forwardauth-authentik@kubernetescrd
  - prefix: "nextcloud"
    service: "nextcloud"
    namespace: "app-nextcloud"
    port: 8080
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: app-nextcloud-nextcloud@kubernetescrd
  - prefix: "authentik.core"
    service: "authentik"
    namespace: "authentik"
    port: 80
global: {}
acmeServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
skipTLSVerify: "false"
