image: "koush/scrypted"
tag: "20-jammy-thin.s6-v0.57.0"

flags:
    enableNodePort: false

persistence:
    media_path:
        enabled: false
        claimName: ""
    conf_path:
        enabled: false
        claimName: ""

resources:
    requests:
        memory: "128Mi"
        cpu: "500m"
    limits:
        memory: "1Gi"
        cpu: "1"
