---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clustet-secret-store
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clustet-secret-store
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clustet-secret-store
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: clustet-secret-store
subjects:
  - kind: ServiceAccount
    name: clustet-secret-store
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: redis
spec:
  provider:
    kubernetes:
      remoteNamespace: "{{ .Release.Namespace }}"
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: "{{ .Release.Namespace }}"
      auth:
        serviceAccount:
          name: "clustet-secret-store"
          namespace: "{{ .Release.Namespace }}"
