---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Values.redis.auth.existingSecret }}"
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: "{{ .Values.redis.auth.existingSecretPasswordKey }}"
data:
