authelia:
  domain: "{{ .Values.global.domain }}"
  configMap:
    default_redirection_url: "https://auth.core.{{ .Values.global.domain }}"
    notifier:
      disable_startup_check: false
      smtp:
        host: postfix.email.svc.cluster.local
        port: 25
        sender: {{ .Values.global.smtp.email }}
        startup_check_address: {{ .Values.global.email }}
        disable_require_tls: true

    # identity_providers:
    #   oidc:
    #     clients: 
    #       - id: nextcloud
    #         description: NextCloud
    #         secret: '$pbkdf2-sha512$310000$flG99HwC8BHSZSFdao0WfA$iBEXWiKkPN7mrd57NrYXTd6MA1/gExEaJfyF3yFPXd3YWMAdHWXtgw7JXfu44w0qCFkzq7fYuJdD9GX2SdH/sA'
    #         public: false
    #         authorization_policy: two_factor
    #         redirect_uris:
    #           - https://nextcloud.{{ .Values.global.domain }}/apps/oidc_login/oidc
    #         scopes:
    #           - openid
    #           - profile
    #           - email
    #           - groups
    #         userinfo_signing_algorithm: none

  persistence:
    storageClass: "{{ .Values.global.nfs.storageClass }}"

    storage:
      postgres:
        host: postgres.chart-database.svc.cluster.local
        database: authelia
        username: authelia

    session:
      redis:
        host: redis-authelia-headless.apps-authelia.svc.cluster.local

redis:
  master:
    persistence:
      storageClass: "{{ .Values.global.nfs.storageClass }}"

  replica:
    persistence:
      storageClass: "{{ .Values.global.nfs.storageClass }}"
