{{- if .Values.secrets.ingresses.secrets.cloudflare }}
cloudflare:
  enabled: true
  tokenSecretName: {{ .Values.secrets.ingresses.secrets.cloudflare.name }}
  tokenSecretKey: api-token
{{- end }}
services:
  # core services
  - prefix: "argocd.core"
    service: "argocd-server"
    namespace: "argocd"
    group: "Core"
    icon: "https://argocd.core.home.sosnovsky.ca/assets/favicon/favicon-32x32.png"
  - prefix: "rancher.core"
    service: "rancher"
    namespace: "chart-rancher"
    group: "Core"
    icon: "https://rancher.core.home.sosnovsky.ca/favicon.png"
  - prefix: "monitoring.core"
    service: prometheus-kube-prometheus-prometheus
    namespace: chart-prometheus
    middleware: "apps-ingresses-chain-authentik"
    group: "Core"
    icon: "https://monitoring.core.home.sosnovsky.ca/favicon.ico"
    port: 9090
  - prefix: "alerts.core"
    service: prometheus-kube-prometheus-alertmanager
    namespace: chart-prometheus
    middleware: "apps-ingresses-chain-authentik"
    group: "Core"
    port: 9093
  - prefix: "grafana.core"
    service: prometheus-grafana
    namespace: chart-prometheus
    middleware: "apps-ingresses-chain-authentik"
    group: "Core"
    icon: "https://grafana.core.home.sosnovsky.ca/public/img/fav32.png"
  - prefix: "authentik.core"
    service: "authentik"
    namespace: "chart-authentik"
    group: "Core"
    icon: "https://authentik.core.home.sosnovsky.ca/static/dist/assets/icons/icon.png"
  # root services
  - prefix: "demo"
    service: "dummy-app"
    namespace: "apps-ingresses"
    middleware: "apps-ingresses-chain-authentik"
    group: "Demo"
    # icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAGPElEQVR42u1bDUyUdRj/iwpolMlcbZqtXFnNsuSCez/OIMg1V7SFONuaU8P1MWy1lcPUyhK1uVbKcXfvy6GikTGKCmpEyoejJipouUBcgsinhwUKKKJ8PD3vnzsxuLv35Q644+Ue9mwH3P3f5/d7n6/3/3+OEJ/4xCc+8YQYtQuJwB0kIp+JrzUTB7iJuweBf4baTlJ5oCqw11C/JHp+tnqBb1ngT4z8WgReTUGbWCBGq0qvKRFcHf4eT/ZFBKoLvMBGIbhiYkaQIjcAfLAK+D8z9YhjxMgsVUGc84+gyx9AYD0khXcMfLCmUBL68HMZ+PnHxyFw3Uwi8B8hgJYh7j4c7c8PV5CEbUTUzBoHcU78iIl/FYFXWmPaNeC3q4mz5YcqJPI1JGKql2Z3hkcjD5EUznmcu6qiNT+Y2CPEoH3Wm4A/QERWQFe9QQ0caeCDlSZJrht1HxG0D3sOuCEiCA1aj4ZY3Ipzl8LiVtn8hxi5zRgWM8YYPBODF/9zxOLcVRVs+YGtwFzxCs1Bo9y+avBiOTQeUzwI3F5+kOwxsXkkmWNHHrjUokqtqtSyysW5gUHV4mtmZEHSdRkl+aELvcFIRN397gPPXD4ZgbxJW1S5OJdA60MgUAyHu1KfAz+pfCUtwr+HuQc8ORQ1jK4ZgGsTvcY5uQP5oYkY2HfcK5sGLpS6l1xZQwNn7Xkedp3OgMrWC1DX0Qwnms/A1rK9cF9atNVo18DP/3o5fF99BGo7LFDRWgMJJQaYQv/PyOcHySP0TITrBIhYb+WSHLrlNGEx5NeXgj2paW8C5rs46h3Dc3kt3G2Ogr9aqoes+f5RvbL1aJ5iXnKnxkfIEoB3N/zHeHAmF9ovwryvYvC9TysnICkEonPX212vvOU8+As6eS+QCDAw0aNLABq6LO8DkJMSSznMMEfScFFGwCJYXbDV7lq17RYIQu+QTYpjRUBM3gZQIt+cOwyTpWRpYBQRsKrgU4ceNS4JkCSxLI1+ZsIS0NvXB6sLE/tL5EQkQJKOm52YON9y7glqJkCSOqzrD6Uvc1wZ1EBA07V/IafmN4ckHG+ugJkSEHuVQQ0ENFy9BLP3R0NR4ymHJGRWFWBnZ6fPVwMBF9EDgrD2z0USqtoaHJKw49SBoZ2dWggIxmcEsvspYLLi4PKNDrvv68OfuKLt/68MqiJAan4Q0IpDm6G7r8fue692X4fI7PiByqA6AqygNh0XHIaClDOkpz9aGVRJABo8CTP+3sqfHZJQeqkSgvHZn+xaqEICKAlhECSGO60MWdVF4IcesDL/ExUSYN3okCrD31fqHZLwcWkq5owPVUoA3UcIgdBv10BrV7vdz3b39kBhw0kVE2BNirG/bqRghyPqIcBKQkKJcVgE1LQ1wR3S5ooqCDBKlSEUzGdyFBNwvq1RTQT0b4BOF5+BgoayCUqAtTLMSXsRzl6uHX8EONoUtXS2KCfAusOsyVwFLV1tznNAuzflAGxb+R/esGuodDcD0bUVbYLelhRf/mWD08ogdYtTjNwYbIsrORhBIwJMPOTWHh1i6Lriz107FUKviivcZvfp8WZvN8TmbVS2rtsHI8mMtn9gSe50KAz79yWw8490OGYpp8lsTUGictd3EA6PHVwB20+mYUNURo/aMs4dhqjsdcoOWGxH5yYu0g0P0EzFBd7DxZoVHY7aHmWtB6VunwhLB6P0gFULk6zhJnvnBw5HW9D9N5GkpQEjMBcQOg+JMBNxjMZgHISawvGZHiKw+0mybv5ozP0txgvk07AQvWxAoh98sXsur3RmwMStxIud9fiIzMAIXTV6yNqxHaH7gg1GA7bgxVvHfEjq1hAl10ZM/A46gO0x0bOPoiHpSEDvsMZhXVVbVRL4TLz2E140EK1dgsnnd9mBaHcmwuigJHeCGLkXvHNaNHOBP4J/HYmoGbGwsJU1ka0nAvM2ht40758ZNmvvRRJ24l3roMa7MxVq4jpRdyMRc8bh9wR0TyIRWdR9hzNXaJs3Ftif6KDWuBcBH0hErky2bNraV5E9jcBjiapE1ExHkO8iEY1OvjLTjAkugezh7ySqFUPoXHTtZAR7ncY4rRrYYgtcCtGHPUgmjEhPmiKXjXc/l4g6HfGJT3ziEw/If86JzB/YMku9AAAAAElFTkSuQmCC"
  - prefix: "nextcloud"
    service: "nextcloud"
    namespace: "apps-nextcloud"
    port: 8080
    middleware: "apps-nextcloud-nextcloud"
    group: "Apps"
    icon: "https://nextcloud.home.sosnovsky.ca/core/img/favicon.ico"
  - prefix: "plex"
    service: "plex"
    namespace: "apps-videohosting"
    port: 32400
    group: "Apps"
    icon: "https://plex.home.sosnovsky.ca/web/favicon.ico"
  - prefix: "frigate"
    service: "frigate"
    namespace: "apps-frigate"
    middleware: "apps-ingresses-chain-authentik"
    group: "Cameras"
    icon: "https://frigate.home.sosnovsky.ca/assets/favicon-92a9ac8b.ico"
  - prefix: "go2rtc"
    service: "go2rtc"
    namespace: "apps-frigate"
    middleware: "apps-ingresses-chain-authentik"
    group: "Cameras"
    icon: "https://frigate.home.sosnovsky.ca/assets/favicon-92a9ac8b.ico"
  - prefix: "main"
    service: "homepage"
    namespace: "chart-homepage"
    middleware: "apps-ingresses-chain-authentik"
    port: 3000
    group: "Core"
  # vh services
  {{- range $k, $v := .Values.videohosting.linuxserverServices }}
  - prefix: "{{ $k }}.vh"
    service: "{{ $k }}"
    namespace: "apps-videohosting"
    port: {{ $v.ports.tcp.web }}
    middleware: "apps-ingresses-chain-authentik"
    group: "Video Hosting"
  {{- end }}