{{ if .Values.secrets.ingresses.secrets.cloudflare }}
cloudflare:
  enabled: true
  tokenSecretName: {{ .Values.secrets.ingresses.secrets.cloudflare.name }}
  tokenSecretKey: api-token
{{ end }}

services:
  - prefix: "argocd.core"
    service: "argocd-server"
    namespace: "argocd"
  - prefix: "monitoring.core"
    service: prometheus-kube-prometheus-prometheus
    namespace: chart-prometheus
    middleware: "apps-ingresses-chain-authentik"
    port: 9090
  - prefix: "alerts.core"
    service: prometheus-kube-prometheus-alertmanager
    namespace: chart-prometheus
    middleware: "apps-ingresses-chain-authentik"
    port: 9093
  - prefix: "grafana.core"
    service: prometheus-grafana
    namespace: chart-prometheus
    middleware: "apps-ingresses-chain-authentik"
  - prefix: "demo"
    service: "dummy-app"
    namespace: "apps-ingresses"
    middleware: "apps-ingresses-chain-authentik"
  - prefix: "nextcloud"
    service: "nextcloud"
    namespace: "apps-nextcloud"
    port: 8080
    middleware: "apps-nextcloud-nextcloud"
  - prefix: "plex"
    service: "plex"
    namespace: "apps-videohosting"
    port: 32400
  {{- range $k, $v := .Values.videohosting.linuxserverServices }}
  - prefix: "{{ $k }}.vh"
    service: "{{ $k }}"
    namespace: "apps-videohosting"
    port: {{ $v.ports.tcp.web }}
    middleware: "apps-ingresses-chain-authentik"
  {{- end }}
  - prefix: "frigate"
    service: "frigate"
    namespace: "apps-frigate"
    middleware: "apps-ingresses-chain-authentik"
  - prefix: "authentik.core"
    service: "authentik"
    namespace: "chart-authentik"