{{- if .Values.secrets.ingresses.secrets.cloudflare }}
cloudflare:
  enabled: true
  tokenSecretName: {{ .Values.secrets.ingresses.secrets.cloudflare.name }}
  tokenSecretKey: api-token
{{- end }}
services:
  # core services
  - prefix: "argocd.core"
    service: "argocd-server"
    namespace: "argocd"
    group: "Core"
    icon: "https://argocd.core.home.sosnovsky.ca/assets/favicon/favicon-32x32.png"
  - prefix: "monitoring.core"
    service: prometheus-kube-prometheus-prometheus
    namespace: chart-prometheus
    middleware: "apps-ingresses-chain-authentik"
    group: "Core"
    icon: "https://monitoring.core.home.sosnovsky.ca/favicon.ico"
    port: 9090
  # - prefix: "alerts.core"
  #   service: prometheus-kube-prometheus-alertmanager
  #   namespace: chart-prometheus
  #   middleware: "apps-ingresses-chain-authentik"
  #   group: "Core"
  #   port: 9093
  - prefix: "grafana.core"
    service: prometheus-grafana
    namespace: chart-prometheus
    middleware: "apps-ingresses-chain-authentik"
    group: "Core"
    icon: "https://grafana.core.home.sosnovsky.ca/public/img/fav32.png"
    health: "healthz"
  # - prefix: "authentik.core"
  #   service: "authentik-server"
  #   namespace: "chart-authentik"
  #   group: "Core"
  #   icon: "https://authentik.home.sosnovsky.ca/static/dist/assets/icons/icon.png"
  # root services
  - prefix: "demo"
    service: "dummy-app"
    namespace: "apps-ingresses"
    middleware: "apps-ingresses-chain-authentik"
    group: "Demo"
  - prefix: "nextcloud"
    service: "nextcloud"
    namespace: "apps-nextcloud"
    port: 8080
    middleware: "apps-nextcloud-nextcloud"
    group: "Apps"
    icon: "https://nextcloud.home.sosnovsky.ca/core/img/favicon.ico"
  - prefix: "plex"
    service: "plex"
    namespace: "apps-videohosting"
    port: 32400
    group: "Apps"
    icon: "https://plex.home.sosnovsky.ca/web/favicon.ico"
  # - prefix: "jellyfin"
  #   service: "jellyfin"
  #   namespace: "apps-videohosting"
  #   port: 8096
  #   group: "Apps"
  - prefix: "main"
    service: "homepage"
    namespace: "chart-homepage"
    middleware: "apps-ingresses-chain-authentik"
    port: 3000
    group: "Core"
  # - prefix: "bazarr.vh"
  #   service: "bazarr"
  #   port: 6767
  #   namespace: "apps-videohosting"
  #   middleware: "apps-ingresses-chain-authentik"
  #   group: "Video Hosting"
  # - prefix: "radarr.vh"
  #   service: "radarr"
  #   namespace: "apps-videohosting"
  #   middleware: "apps-ingresses-chain-authentik"
  #   group: "Video Hosting"
  # - prefix: "sonarr.vh"
  #   service: "sonarr"
  #   namespace: "apps-videohosting"
  #   middleware: "apps-ingresses-chain-authentik"
  #   group: "Video Hosting"
  # - prefix: "prowlarr.vh"
  #   service: "prowlarr"
  #   namespace: "apps-videohosting"
  #   middleware: "apps-ingresses-chain-authentik"
  #   group: "Video Hosting"
  # - prefix: "readarr.vh"
  #   service: "readarr"
  #   namespace: "apps-videohosting"
  #   middleware: "apps-ingresses-chain-authentik"
  #   group: "Video Hosting"
  # webapp services
  {{- $webapps := .Files.Get (printf "apps-values/%s" .Values.apps.webapps.valuesFile) }}
  {{- $webapps := tpl $webapps . | fromYaml }}
  {{- range $k, $v := $webapps.apps }}
  {{ if $v.enabled }}
  - prefix: "{{ $v.ingress.prefix | default (printf "%s-app" $k) }}"
    service: "{{ $k }}"
    namespace: "apps-webapps"
    useDirectPrefix: {{ $v.ingress.useDirectPrefix | default "false" }}
    useSecondaryDomain: {{ $v.ingress.useSecondaryDomain | default "false" }}
    port: {{ $v.ports.tcp.web }}
    {{- if $v.ingress }}
    middleware: {{ $v.ingress.middleware | default "apps-ingresses-chain-authentik" }}
    {{ else }}
    middleware: "apps-ingresses-chain-authentik"
    {{ end -}}
    group: {{ .ingress.group | default "Basic Webapps" }}
  {{ end }}
  {{- end }}