
photoprism:
    site:
        caption: "Sosnovsky Photos"
        description: "Family Photos"
        authtor: "{{ .Values.global.email }}"
        url: "https://photoprism.{{ .Values.global.domain }}"
    volumes:
        originals: {{ .Values.global.nfs.additionalShares.familyphotos }}
        import: ~
        storage: {{ .Values.storage.photoprism.name }}
        additional: []
    auth:
        secretName: {{ .Values.secrets.photoprism.secrets.auth.name }}

database:
    storageClass: {{ .Values.global.nfs.storageClass  }}
    auth:
        secretName: {{ .Values.secrets.photoprism.secrets.db.name }}
