nfs:
  shares:
    torrents: "/mnt/EightTerra/DownloadedTorrents"
    family-videos: "/mnt/EightTerra/FamilyStorage/Video"
plex:
  repo: "plexinc/pms-docker"
  tag: "1.31.3.6868-28fc46b27"
transmission:
  repo: lscr.io/linuxserver/transmission
  tag: "4.0.2"
sonarr:
  repo: lscr.io/linuxserver/sonarr
  tag: "3.0.10"
