services:
  bumper:
    image: ghcr.io/mvladislav/bumper:develop
    restart: always
    volumes:
      data: /bumper/data
      certs: /bumper/certs
    ports:
      - port: '443'
        name: https
      - port: '8007'
        name: '8007'
      - port: '8883'
        name: http
      - port: '5223'
        name: '5223'
    annotations:
      "metallb.universe.tf/loadBalancerIPs" : "10.0.100.3"
      "metallb.io/ip-allocated-from-pool" : "homelab-pool"
    serviceType: LoadBalancer
    environment:
      BUMPER_DATA: /bumper/data
      BUMPER_PROXY_WEB: true
      BUMPER_PROXY_MQTT: true
      NETWORK_MODE: overlay
      BUMPER_ANNOUNCE_IP: "10.0.100.3"
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
      BUMPER_LISTEN: 0.0.0.0

volumes:
  data:
    type: nfs-provider
    size: 200Mi
  certs:
    type: nfs-provider
    size: 50Mi

secrets:
  immich-shared:
    - name: DB_USERNAME
      aliases:
        - POSTGRES_USER  
      value: immich
    - name: DB_DATABASE_NAME
      aliases:
        - POSTGRES_DB
      value: immich
    - name: DB_HOSTNAME
      value: database
    - name: REDIS_HOSTNAME
      value: redis

externalSecrets:
  generators:
    db-password:
      length: 16
      digits: 5
      symbols: 5
      symbolCharacters: "-_$@"
      noUpper: false
      allowRepeat: true
  secrets:
    db-password:
      refreshPolicy: "CreatedOnce"
      target:
        name: immich-shared
        creationPolicy: Merge
        deletionPolicy: Merge
        template:
          engineVersion: v2
          data:
            POSTGRES_PASSWORD: "{{`{{.password}}`}}"
            DB_PASSWORD: "{{`{{.password}}`}}"
      dataFrom:
        - sourceRef:
            generatorRef:
                apiVersion: generators.external-secrets.io/v1alpha1
                kind: Password
                name: "db-password"
ingress:
  enabled: true
  prefix: immich
  service: immich-server
  port: 2283