services:
  smartboi:
    image: minipc1.lab.internal:5001/smartboi:latest
    ports:
      - port: "8000"
    restart: always
    environment:
      SMARTBOI_db__file: /app/db/smartboi.db
      SMARTBOI_agent__base_url: http://fwdesk.lab.internal:11434
    volumes:
      db: /app/db/

volumes:
  db:

ingress:
  enabled: true
  prefix: smartboi
  service: smartboi
  port: 8000
  useSecondaryDomain: true
