---
apiVersion: v1
kind: Secret
metadata:
    name: factory-creds
    annotations:
        secret-generator.v1.mittwald.de/autogenerate: KERBEROS_LOGIN_PASSWORD
type: Opaque
data:
    KERBEROS_LOGIN_USERNAME: {{ "kerbos" | b64enc }}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "mongodb-secret"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.mongodb.secret.store }}
  target:
    name: "factory-creds"
    creationPolicy: Merge
  data:
    - secretKey: "MONGODB_DATABASE_CREDENTIALS"
      remoteRef:
        key: {{ .Values.mongodb.secret.name }}
        property: {{ .Values.mongodb.secret.keys.credentials }}
    - secretKey: "MONGODB_USERNAME"
      remoteRef:
        key: {{ .Values.mongodb.secret.name }}
        property: {{ .Values.mongodb.secret.keys.username }}
    - secretKey: "MONGODB_PASSWORD"
      remoteRef:
        key: {{ .Values.mongodb.secret.name }}
        property: {{ .Values.mongodb.secret.keys.password }}
    - secretKey: "MONGODB_DATABASE_STORAGE"
      remoteRef:
        key: {{ .Values.mongodb.secret.name }}
        property: {{ .Values.mongodb.secret.keys.storage }}

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: factory-config
data:
    NAMESPACE: {{ .Release.Namespace }}
    KERBEROS_AGENT_IMAGE: "kerberos/agent:{{ .Values.agent.version }}" 
    KERBEROS_AGENT_MEMORY_LIMIT: {{ .Values.agent.memory }}
    FACTORY_ENVIRONMENT: "kubernetes"
    K8S_PROXY: http://localhost:8082
    FACTORY_API_URL: "api.kerberos.{{ .Values.global.domain }}"
    MONGODB_HOST: {{ .Values.mongodb.host }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: factory
spec:
    replicas: 1
    selector:
        matchLabels:
            kerberos/app: factory
    minReadySeconds: 10
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    template:
        metadata:
            labels:
                kerberos/app: factory
        spec:
            containers:
                -   name: factory
                    image: "kerberos/factory:{{ $.Chart.AppVersion }}"
                    ports:
                        -   containerPort: 80
                        -   containerPort: 8082
                    envFrom:
                        -   configMapRef:
                                name: factory-config
                        -   secretRef:
                                name: factory-creds

---
apiVersion: v1
kind: Service
metadata:
    name: factory
    labels:
        kerberos/app: factory
spec:
    ports:
        -   port: 80
            targetPort: 80
            name: frontend
            protocol: TCP
        -   port: 8082
            name: backend
            targetPort: 8082
            protocol: TCP
    selector:
        kerberos/app: factory

