apiVersion: v1
kind: Secret
metadata:
  name: agent-secret-envs
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: AGENT_PASSWORD
type: Opaque
data:
  AGENT_USERNAME: "{{ 'kerbos' | b64enc }}"

