# ---
# apiVersion: cert-manager.io/v1alpha2
# kind: ClusterIssuer
# metadata:
#   name: "{{ $.Release.Name }}.letsencrypt"
#   namespace: {{ $.Release.Namespace }}
# spec:
#   acme:
#     server: {{ $.Values.acme_server }}
#     email: {{ $.Values.email }}
#     skipTLSVerify: {{ $.Values.skipTLSVerify }}
#     privateKeySecretRef:
#       name: "{{ $.Release.Name }}.letsencrypt"
#     solvers:
#     - http01:
#         ingress:
#           class: traefik