{{ range $serviceName, $service := .Values.services -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $.Release.Name }}-{{ $serviceName }}"
  namespace: {{ $.Release.Namespace }}
  annotations:
  {{  if (and $.Values.tlsEnable (not $service.tlsDisabled) )  }}
    cert-manager.io/cluster-issuer: letsencrypt
  {{- end }}
  {{- if $service.annotations -}}
    {{- range $k, $v := $service.annotations }}
    {{ $k -}}: "{{- $v -}}"
    {{- end }}
  {{ end }}
spec:
  {{- if (and $.Values.tlsEnable (not $service.tlsDisabled) ) }}
  tls:
    - secretName: "homelab.{{ $.Release.Name }}.cert.{{ $serviceName }}"
      hosts:
        - {{ $service.host }}
  {{- end }}
  rules:
  - host: {{ $service.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ $serviceName }}
            port: 
            {{- $service.port | default (dict "port" 80) | toYaml | nindent 14 }}
        path: {{ $service.path | default "/" }}
        pathType: Prefix
{{ end }}
