---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-redis-secrets
type: Opaque
stringData:
  AUTHELIA_SESSION_REDIS_HOST: "authelia-redis.{{ .Release.Namespace }}.svc.cluster.local"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authelia-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "authelia-redis"
  serviceName: authelia-redis
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "authelia-redis"
    spec:
      containers:
        -   name: redis
            image: {{ .Values.authelia.redis.image }}
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: data
                mountPath: /var/lib/postgresql/data
            ports:
              - containerPort: 6379
            livenessProbe:
                tcpSocket:
                  port: 6379
                initialDelaySeconds: 10  
                periodSeconds: 5         
                timeoutSeconds: 1        
                failureThreshold: 3     
            readinessProbe:
                tcpSocket:
                  port: 6379
                initialDelaySeconds: 10  
                periodSeconds: 5         
                timeoutSeconds: 1        
                failureThreshold: 3      
            resources: 
                requests:
                    cpu: 1
                    memory: 5Gi
                limits:
                    cpu: 1
                    memory: 5Gi
---
kind: Service
apiVersion: v1
metadata:
  name: authelia-redis
spec:
  selector:
    app.kubernetes.io/name: "authelia-redis"
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
