---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: authelia-keys
spec:
  length: 64
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true

---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets

{{ range $k := (list "AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET" "AUTHELIA_SESSION_SECRET" "AUTHELIA_STORAGE_ENCRYPTION_KEY") }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "authelia-secrets-{{ $k | sha256sum | substr 0 30 }}"
spec:
  refreshInterval: "30m"
  target:
    name: authelia-secrets
    creationPolicy: Merge
    deletionPolicy: Merge
    template:
      engineVersion: v2
      data:
        "{{ $k }}": "{{`{{.password}}`}}"

  dataFrom:
    - sourceRef:
        generatorRef:
            apiVersion: generators.external-secrets.io/v1alpha1
            kind: Password
            name: "authelia-keys"

{{ end }}