---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth
spec:
  forwardAuth:
    address: auth.{{ .Values.global.dns.primary.domain }}/api/authz/forward-auth'
    trustForwardHeader: true
    authResponseHeaders:
        - 'Remote-User'
        - 'Remote-Groups'
        - 'Remote-Email'
        - 'Remote-Name'