---
apiVersion: traefik.io/v1alpha1
kind: 'Middleware'
metadata:
  name: forward-auth
  labels:
    app.kubernetes.io/name: 'authelia'
spec:
  forwardAuth:
    address: 'http://authelia.{{ .Release.Namespace }}.svc.cluster.local/api/authz/forward-auth'
    authResponseHeaders:
      - 'Remote-User'
      - 'Remote-Groups'
      - 'Remote-Email'
      - 'Remote-Name'
