version: '3'

services:
  app:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ../..:/workspaces:cached
      - "~/.ssh:/home/vscode/.ssh"
      - "~/.gitconfig:/home/vscode/.gitconfig"

    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    environment:
      - KUBE_EDITOR="code -w"
    # serverlb:
    #   image: docker.io/rancher/k3s:v1.25.6-k3s1
