---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: database
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  revisionHistoryLimit: 2
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: storage
        finalizers:
          - kubernetes.io/pvc-protection
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.database.storageClass }}
        resources: 
          requests:
            storage: 10Gi
          limits:
            storage: 100Gi
  template:
    metadata:
      labels:
        app: database
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: homelab/capacity
                  operator: In
                  values:
                    - med
                    - low
      containers:
        - name: app
          image: "{{ .Values.database.image.repo }}:{{ .Values.database.image.tag }}"
          envFrom:
            - configMapRef: 
                name: database-envs
          env:
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.auth.secretName }}
                  key: {{ .Values.database.auth.secretKeys.username }}
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.auth.secretName }}
                  key: {{ .Values.database.auth.secretKeys.database }}
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.auth.secretName }}
                  key: {{ .Values.database.auth.secretKeys.password }}
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.auth.secretName }}
                  key: {{ .Values.database.auth.secretKeys.password }}
          resources: {}
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: storage
              mountPath: /var/lib/mysql