---
kind: Service
apiVersion: v1
metadata:
  name: photoprism
spec:
  selector:
    app: photoprism
  type: ClusterIP
  ports:
    - port: 2342
      targetPort: 2342
      name: "http"
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.database.service.name }}
spec:
  selector:
    app: database
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      name: "http"
