apiVersion: v2
name: photos
description: An apps service for homelab
type: application
version: 0.1.0
appVersion: "edge"
dependencies: 
  - name: redis
    alias: immich-redis
    condition: redis.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 17.11.6