
global:
  timezone: changeme
  nfs:
    storageClass: changeme

immich:
  shared:
    version: v1.88.2
    libraryMountPath: /usr/src/app/upload
    libraryMounSubtPath: "Pictures"
    libraryPVC:
      nfs:
        path: changeme
        server: changeme
  apps:
    server:
      replicas: 1
      port: 80
      image: ghcr.io/immich-app/immich-server
      livenessProbe:
        failureThreshold: 3
        httpGet:
            path: /server-info/ping
            port: http
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
      readinessProbe:
          failureThreshold: 3
          httpGet:
              path: /server-info/ping
              port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
    microservices:
      replicas: 1
      port: 80
      image: ghcr.io/immich-app/immich-server
      args:
        - ./start-microservices.sh
      env:
        - name: REVERSE_GEOCODING_DUMP_DIRECTORY
          value: /geodata-cache
      persistence:
        geodata-cache:
          mountPath: /geodata-cache
          accessModes:
              - ReadWriteMany
          resources:
            limits:
              storage: 5Gi
            requests:
              storage: 5Gi
      livenessProbe:
        failureThreshold: 3
        httpGet:
            path: /server-info/ping
            port: http
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
      readinessProbe:
          failureThreshold: 3
          httpGet:
              path: /server-info/ping
              port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
    machineLearning:
      replicas: 1
      port: 80
      image: ghcr.io/immich-app/immich-machine-learning
      env:
        - name: TRANSFORMERS_CACHE
          value: /cache
      persistence:
        cache:
          mountPath: /cache
          accessModes:
              - ReadWriteMany
          resources:
            limits:
              storage: 5Gi
            requests:
              storage: 5Gi
      livenessProbe:
          failureThreshold: 3
          httpGet:
              path: /ping
              port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
      readinessProbe:
          failureThreshold: 3
          httpGet:
              path: /ping
              port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
    typesense:
      port: 8108
      image: docker.io/typesense/typesense
      version: 0.24.0
      env:
        - name: TYPESENSE_DATA_DIR
          value: /tsdata
      persistence:
        tsdata:
          mountPath: /tsdata
          accessModes:
              - ReadWriteMany
          resources:
            limits:
              storage: 5Gi
            requests:
              storage: 5Gi
      livenessProbe:
          failureThreshold: 3
          httpGet:
              path: /health
              port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
      readinessProbe:
          failureThreshold: 3
          httpGet:
              path: /health
              port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1

redis:
  enabled: false
  architecture: standalone
  auth:
    enabled: false




# ## This chart relies on the common library chart from bjw-s
# ## You can find it at https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
# ## Refer there for more detail about the supported values

# # These entries are shared between all the Immich components

# env:
#   REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
#   DB_HOSTNAME: "{{ .Release.Name }}-postgresql"
#   DB_USERNAME: "{{ .Values.postgresql.global.postgresql.auth.username }}"
#   DB_DATABASE_NAME: "{{ .Values.postgresql.global.postgresql.auth.database }}"
#   # -- You should provide your own secret outside of this helm-chart and use `postgresql.global.postgresql.auth.existingSecret` to provide credentials to the postgresql instance
#   DB_PASSWORD: "{{ .Values.postgresql.global.postgresql.auth.password }}"
#   TYPESENSE_ENABLED: "{{ .Values.typesense.enabled }}"
#   TYPESENSE_API_KEY: "{{ .Values.typesense.env.TYPESENSE_API_KEY }}"
#   TYPESENSE_HOST: '{{ printf "%s-typesense" .Release.Name }}'
#   IMMICH_WEB_URL: '{{ printf "http://%s-web:3000" .Release.Name }}'
#   IMMICH_SERVER_URL: '{{ printf "http://%s-server:3001" .Release.Name }}'
#   IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'

# image:
#   tag: v1.79.1

# immich:
#   persistence:
#     # Main data store for all photos shared between different components.
#     library:
#       # Automatically creating the library volume is not supported by this chart
#       # You have to specify an existing PVC to use
#       existingClaim:

# # Dependencies

# postgresql:
#   enabled: false
#   global:
#     postgresql:
#       auth:
#         username: immich
#         database: immich
#         password: immich


# typesense:
#   enabled: true
#   env:
#     TYPESENSE_DATA_DIR: /tsdata
#     TYPESENSE_API_KEY: typesense
#   persistence:
#     tsdata:
#       enabled: true
#       accessMode: ReadWriteOnce
#       size: 1Gi
#       # storageClass: storage-class
#   image:
#     repository: docker.io/typesense/typesense
#     tag: 0.24.0
#     pullPolicy: IfNotPresent

# # Immich components

# server:
#   enabled: true
#   image:
#     repository: ghcr.io/immich-app/immich-server
#     pullPolicy: IfNotPresent

# microservices:
#   enabled: true
#   env:
#     REVERSE_GEOCODING_DUMP_DIRECTORY: /geodata-cache
#   persistence:
#     geodata-cache:
#       enabled: true
#       size: 1Gi
#       accessMode: ReadWriteMany
#       # storageClass: your-class
#   image:
#     repository: ghcr.io/immich-app/immich-server
#     pullPolicy: IfNotPresent

# machine-learning:
#   enabled: true
#   image:
#     repository: ghcr.io/immich-app/immich-machine-learning
#     pullPolicy: IfNotPresent
#   env:
#     TRANSFORMERS_CACHE: /cache
#   persistence:
#     cache:
#       enabled: true
#       size: 10Gi
#       accessMode: ReadWriteMany
#       # storageClass: your-class

# web:
#   enabled: true
#   image:
#     repository: ghcr.io/immich-app/immich-web
#     pullPolicy: IfNotPresent
#   persistence:
#     library:
#       enabled:  true
#       size: 10Gi
#       accessMode: ReadWriteMany

# proxy:
#   enabled: true
#   image:
#     repository: ghcr.io/immich-app/immich-proxy
#     pullPolicy: IfNotPresent

#   persistence:
#     library:
#       enabled:  true
#       size: 10Gi
#       accessMode: ReadWriteMany

#   ingress:
#     main:
#       enabled: false
#       annotations:
#         # proxy-body-size is set to 0 to remove the body limit on file uploads
#         nginx.ingress.kubernetes.io/proxy-body-size: "0"
#       hosts:
#         - host: immich.local
#           paths:
#             - path: "/"
#       tls: []