

images:
    frigate:
        repo: "ghcr.io/blakeblackshear/frigate"
        tag: "0.12.1"
    go2rtc:
        repo: "alexxit/go2rtc"
        tag: "latest"

persistence:
    media_path:
        enabled: false
        claimName: ""
    conf_path:
        enabled: false
        claimName: ""

resources:
    frigate:
        requests:
            memory: "1Gi"
            cpu: "2"
        limits:
            memory: "1Gi"
            cpu: "2"
    go2rtc:
        requests:
            memory: "1Gi"
            cpu: "1"
        limits:
            memory: "1Gi"
            cpu: "1"
