coral:
    enabled: true

affinity:
    nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
            -   weight: 1
                preference:
                matchExpressions:
                    -   key: "homelab/coral_device"
                        operator: In
                        values: ["true"]