

images:
    frigate:
        repo: "ghcr.io/blakeblackshear/frigate"
        tag: "stable"
    go2rtc:
        repo: "alexxit/go2rtc"
        tag: "latest"
    scrypted:
        repo: "ghcr.io/koush/scrypted"
        tag: "v0.57.0"


persistence:
    media_path:
        enabled: false
        claimName: ""
    conf_path:
        enabled: false
        claimName: ""

affinity: {}

coral:
    enabled: false
    hostPath: /dev/bus/usb

resources:
    frigate:
        requests:
            memory: "4Gi"
            cpu: "2"
        limits:
            memory: "4Gi"
            cpu: "3"
    go2rtc:
        requests:
            memory: "100Mi"
            cpu: "500m"
        limits:
            memory: "500Mi"
            cpu: "1"
