coral:
    enabled: true

affinity:
    nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
                -   matchExpressions:
                    -   key: "homelab/coral_device"
                        operator: In
                        values:
                            - "true"
