{{ define "homelab.argo.project" }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: {{ .description }}
  orphanedResources:
    warn: false
  sourceRepos:
    - "*"
  destinations:
    - server: "*"
      namespace: '*'
      name: '*'
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
{{ end }}