---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dummy-app
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: dummy
        release: "{{ .Release.Name }}"
    spec:
      containers:
        - name: name
          image: nginxdemos/hello
          resources:
            limits:
              cpu: 1
              memory: 1Gi
          ports:
            - containerPort: 80
