---
apiVersion: v1
kind: ConfigMap
metadata:
  name: z2m-config
data:
  configuration.yaml: |-
        permit_join: true
        # mqtt:
            # base_topic: zigbee2mqtt
            # server: mqtt://mqtt
        serial:
            port: /dev/ttyUSB0
        frontend:
        port: 8080
        advanced:
            network_key: GENERATE