---
apiVersion: v1
kind: ConfigMap
metadata:
  name: z2m-config
data:
  configuration.yaml: |-
        permit_join: true
        homeassistant: true
        advanced:
            log_level: debug
        mqtt:
            base_topic: "zigbee2mqtt"
            server: "mqtt://{{.Values.global.mqtt.host}}:{{.Values.global.mqtt.port}}"
            user: "{{.Values.global.mqtt.username}}"
            password: "{{.Values.global.mqtt.password}}"
        serial:
            port: "tcp://ser2sock.{{ .Release.Namespace }}.svc.cluster.local:10000"
        frontend:
            port: "8080"
        advanced:
            network_key: "GENERATE"
        devices: /data/devices.yaml
        groups: /data/groups.yaml