---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    {{ .Release.Name }}/app: z2m
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-node-port
spec:
  selector:
    {{ .Release.Name }}/app: z2m
  type: NodePort
  ports:
    - port: 80
      nodePort: 30100
      targetPort: 8080
      name: http
      protocol: TCP