global:
    timezone: "changeme"

common:
    storageClaimName: "changeme"
    resources:
        limits:
            cpu: "3"
            memory: "2Gi"
        requests:
            cpu: "1"
            memory: "200Mi"

cameras:
    - name: "Baby Room"
      rtsp:
          url_main: "rtsp://motioneye:v1eWme123@192.168.0.11:554/cam/realmonitor?channel=1&subtype=0"
          url_sub: "rtsp://motioneye:v1eWme123@192.168.0.11:554/cam/realmonitor?channel=1&subtype=1"
