global:
    domain: "change.me"

agent:
    version: "9d70778"
    memory: "256Mi"

mongodb:
    host: "?"
    secret:
        store: "?"
        name: "?"
        keys:
            credentials: "?"
            username: "?"
            password: "?"
            storage: "?"