---
kind: Service
apiVersion: v1
metadata:
  name: transmission
spec:
  selector:
    app: transmission
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      name: "web"
    - port: 51413
      targetPort: 51413
      name: "51413"
    - port: 51413
      targetPort: 51413
      protocol: UDP
      name: "51413-udp"
