{{- $argoappsetApps := "apps" -}}
{{ include "homelab.argo.project" (dict "name" $argoappsetApps "description" "common applications")}}


{{ range $appName, $appProps := .Values.apps }}

{{ if (not $appProps.disabled) }}

{{- $genNamespace := (printf "apps-%s" $appName) -}}

{{ if (not $appProps.namespace) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ $genNamespace }}"
{{ end }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-{{ $appName }}
spec:
  project: {{ $argoappsetApps }}
  source:
    repoURL: "git@github.com:{{ $.Values.gitops.repo }}.git"
    targetRevision: "{{ $.Values.gitops.commit }}"
    path: 'k8s/apps/{{ $appName }}'
    helm:
        valueFiles:
            - values.yaml
            - values-{{$.Values.global.deployment}}.yaml
        values: |-
{{- $values := ($appProps.values| default "")  -}}
{{ if $appProps.valuesFile }}
{{- $valuesFilePath := (printf "apps-values/%s" $appProps.valuesFile) -}}
{{- $values := $.Files.Get $valuesFilePath -}}
        {{- tpl $values $ | nindent 10 -}}
{{- else -}}
        {{- tpl $values $ | nindent 10 -}}
{{- end }}
          global: 
              {{- $.Values.global | toYaml | nindent 12 }}
        releaseName: {{ $appName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $appProps.namespace | default $genNamespace }}
  {{ if $appProps.syncPolicy }}
  syncPolicy:
    {{$appProps.syncPolicy | toYaml | nindent 4 }}
  {{ end }}
{{ end }}
{{ end }}
