{{- $infraChartProjectName := "infrastructure-charts" -}}
{{ include "homelab.argo.project" (dict "Values" $.Values "name" $infraChartProjectName "description" "infrastructure helm charts")}}

{{ range $chartName, $chartProps := .Values.infrastructureCharts }}

{{- $namespace := (printf "chart-%s" $chartName) -}}

---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ $namespace }}"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chart-{{ $chartName }}
spec:
  project: {{ $infraChartProjectName }}
  source:
    chart: {{ $chartProps.chart | default $chartName }}
    repoURL: {{ $chartProps.repoURL }}
    targetRevision: {{ $chartProps.targetRevision }}
    helm:
      values: |-
        {{- tpl ($chartProps.values | default "") $ | nindent 8}}
      releaseName: {{ $chartName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $namespace }}
  syncPolicy:
    automated:
      selfHeal: true
{{ end }}