{{ range $secretsNS, $secrets := .Values.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ $secretsNS }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ $secretsNS }}
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: {{ $secretsNS }}
      auth:
        serviceAccount:
          name: {{ $secretsNS }}
          namespace: {{ $secretsNS }}


{{ range $key, $value := $secrets.named }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $value.name }}
  namespace: {{ $secretsNS }}
  annotations:
    homelab-secret/type: "externally-filled"
data:
  _placeholder: ""
{{ end }}

{{ end }}
