{{ range $_, $secretsData := .Values.secrets }}

{{ if $secretsData.enableClusterStore }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager-{{ $secretsData.namespace }}
  namespace: {{ $secretsData.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get"]
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: secret-manager-{{ $secretsData.namespace }}
  namespace: {{ $secretsData.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-{{ $secretsData.namespace }}
  namespace: {{ $secretsData.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-manager-{{ $secretsData.namespace }}
subjects:
- kind: ServiceAccount
  name: secret-manager-{{ $secretsData.namespace }}
  namespace: {{ $secretsData.namespace }}

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ $secretsData.namespace }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ $secretsData.namespace }}
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: {{ $secretsData.namespace }}
      auth:
        serviceAccount:
          name: secret-manager-{{ $secretsData.namespace }}
          namespace: {{ $secretsData.namespace }}
{{ end }}


{{ range $key, $value := $secretsData.secrets }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $value.name }}
  namespace: {{ $secretsData.namespace }}
  annotations:
    homelab-secret/type: "externally-filled"
    {{ if $secretsData.autogenerated }}
    secret-generator.v1.mittwald.de/autogenerate: {{ join "," $secretsData.autogenerated | quote }}
    {{ end }}
data:
{{- if $value.data }}
  {{- tpl $value.data $ | nindent 4}}
{{ else }}
  _placeholder: ""
{{ end }}

{{ range $ekey, $evalue := ($value.external | default (dict)) }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $value.name }}-{{ $ekey }}
  namespace: {{ $secretsData.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $evalue.store }}
  target:
    name: {{ $value.name }}
    creationPolicy: Merge
  data:
    - secretKey: {{ $ekey }}
      remoteRef:
        key: {{ $evalue.secretName }}
        property: {{ $evalue.secretKey }}
{{ end }}

{{ end }}



{{ end }}
