{{ $secretsNS := .Values.secrets.namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ $secretsNS }}"
---

{{ range $key, $value := .Values.secrets.named }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $value.name }}
  namespace: {{ $secretsNS }}
  annotations:
    homelab-secret/type: "externally-filled"
data:
  _placeholder: ""
  {{ tpl ($value.content | default "") $ | toYaml }}
{{ end }}
