{{ range $key, $value := .Values.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $value.name }}
  namespace: {{ $value.namespace }}
spec:
  storageClassName: {{ $.Values.global.nfs.storageClass }}
  accessModes: 
    {{- $value.accessModes | toYaml | nindent 4 }}
  resources:
    {{- $value.resources | toYaml | nindent 4 }}
{{ end }}