argo-cd:
  configs:
    params:
      server.insecure: true
      server.basehref: /
      server.rootpath: ""
  crds:
    install: true
    keep: false
  server:
    ingress:
      enabled: false
    ingressGrpc:
      enabled: false
selfapp:
  commit: "stable"
  repo: "asosnovsky/homelab"
  sshkey: ""
global:
  email: "ariel@sosnovsky.ca"
  tls:
    enabled: false
    issuer: ""
    secretName: ""
  domain: ""
  deployment: ""
