argo-cd:
  crds:
    install: true
    keep: false
  server:
    ingress:
      enabled: true
      hosts: 
        - "argocd.home.sosnovsky.ca"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
        - hosts:
            - argocd.home.sosnovsky.ca
          secretName: homelab.ingress.cert.argocd
selfapp:
  commit: "stable"
  repo: "asosnovsky/homelab"
  sshkey: ""
  traefikRule: Host(`argocd.home.sosnovsky.ca`)
