argo-cd:
  config:
    params:
      server.insecure: true
      server.basehref: /
      server.rootpath: ""
  crds:
    install: true
    keep: false
  server:
    ingress:
      enabled: false
    ingressGrpc:
      enabled: false
selfapp:
  commit: "stable"
  repo: "asosnovsky/homelab"
  sshkey: ""
