authentik:
  cookie_domain: authentik.core.{{ .Values.global.rootSubDomain }}.{{ .Values.global.domain }}
  email:
    from: {{ .Values.global.smtp.email }}
    host: postfix.email.svc.cluster.local
    port: 25
    username: {{ .Values.global.smtp.email }}
    use_ssl: false
  postgresql:
    host: postgres.chart-database.svc.cluster.local
    name: authentik
    user: authentik
postgresql:
  enabled: false
redis:
  enabled: true
global:
  envFrom:
    - secretRef:
        name: {{ .Values.secrets.authentik.secrets.env.name }}
  ingress:
    enabled: true
    annotations: 
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/group: Core
      gethomepage.dev/icon: 'https://authentik.core.home.{{ .Values.global.domain }}/static/dist/assets/icons/icon.png'
      gethomepage.dev/name: authentik@chart-authentik
      gethomepage.dev/siteMonitor: 'http://authentik-server.chart-authentik.svc.cluster.local:80/'
    hosts: 
      - authentik.core.home.{{ .Values.global.domain }}
    pathType: Prefix
    tls: 
      - hosts:
          - authentik.core.home.{{ .Values.global.domain }}
        secretName: tls-authentik.core.home.{{ .Values.global.domain }}
    https: true

