fullnameOverride: "postgres"
image:
  tag: 15.1.0-debian-11-r19
  repository: bitnami/postgresql
  pullPolicy: IfNotPresent
auth:
  secretKeys:
    adminPasswordKey: password
  existingSecret: "{{ .Values.secrets.database.secrets.dbmain.name }}"
architecture: standalone
postgresqlDataDir: /bitnami/postgresql/data
primary:
  persistence:
    enabled: true
    mountPath: /bitnami/postgresql
    storageClass: "{{ .Values.global.nfs.storageClass }}"
    existingClaim: "{{ .Values.storage.database.name }}"
    accessModes:
    - ReadWriteMany
readReplicas:
  replicaCount: 0
