config:
  widgets:
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  services: 
    - Local Cameras:
        - Korie:
            href: http://korie.amc.cam.local/
        - Eddie:
            href: http://eddie.amc.cam.local/
        - Living Room:
            href: http://lr.tapo.cam.local/
    - Routers:
        - GL Main:
            href: http://gl.router.local
        - GL Basement:
            href: http://basement.router.local
        - TPlink Main:
            href: http://tp.router.local
  bookmarks: []
  kubernetes:
    mode: cluster


serviceAccount:
  create: true
  name: homepage

enableRbac: true

image:
  tag: v0.7.4