image:
  repository: ghcr.io/gethomepage/homepage
  tag: latest
config:
  widgets:
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  services: 
    - Local Cameras:
        - Korie:
            href: http://korie.cam.internal/
        - Eddie:
            href: http://eddie.cam.internal/
        - Living Room:
            href: http://livingroom.cam.internal/
        - Doorbell:
            href: 'http://doorbell.cam.internal'
        - Garage:
            href: 'http://garage.cam.internal'
    - Routers:
        - GL Main:
            href: http://gl.router.internal
        - GL Basement:
            href: http://gl-basement.router.internal
        - MainMesh:
            href: http://velica-main.router.internal	
        - MeshNode1:
            href: http://velica-node1.router.internal	
        - MeshNode2:
            href: http://velica-node2.router.internal	
  bookmarks: []
  kubernetes:
    mode: cluster


serviceAccount:
  create: true
  name: homepage

enableRbac: true
