config:
  widgets:
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  services: []
  bookmarks: []
  kubernetes:
    mode: cluster


serviceAccount:
  create: true
  name: homepage

enableRbac: true