cleanPrometheusOperatorObjectNames: false
alertmanager:
  alertmanagerSpec:
    storage: 
        volumeClaimTemplate:
            spec:
                storageClassName: {{ .Values.global.nfs.storageClass }}
                accessModes: ["ReadWriteOnce"]
                resources:
                    requests:
                        storage: 50Gi
                    limits:
                        storage: 100Gi

{{-  if .Values.global.tls.enabled  }}
    externalUrl: "https://alerts.core.{{ .Values.global.domain }}"
{{- else }}
    externalUrl: "http://alerts.core.{{ .Values.global.domain }}"
{{- end }}
    resources: 
        requests:
            memory: 400Mi
        limits:
            memory: 2Gi

  config:
    global:
        smtp_from: '{{.Values.global.smtp.email }}'
        smtp_smarthost: 'postfix.email.svc.cluster.local:25'
        smtp_hello: 'alerts.core.{{ .Values.global.domain }}'
    receivers:
        -   name: '{{ .Values.global.email }}'
            email_configs: 
                -   to: '{{ .Values.global.email }}'

grafana:
  defaultDashboardsTimezone: {{ .Values.global.timezone }}
  adminPassword: prom-operator
  persistence:
    type: pvc
    enabled: true
    storageClassName: {{ .Values.global.nfs.storageClass }}
  envFromConfigMaps:
    -   name: {{ .Values.secrets.prometheus.configmaps.auth.name }}
        optional: true

prometheus:
  prometheusSpec:
    enableAdminAPI: false

{{-  if .Values.global.tls.enabled  }}
    externalUrl: "https://monitoring.core.{{ .Values.global.domain }}"
{{- else }}
    externalUrl: "http://monitoring.core.{{ .Values.global.domain }}"
{{- end }}
    resources: 
        requests:
            memory: 400Mi
        limits:
            memory: 2Gi
    storageSpec: 
        volumeClaimTemplate:
            spec:
                storageClassName: {{ .Values.global.nfs.storageClass }}
                accessModes: ["ReadWriteOnce"]
                resources:
                    requests:
                        storage: 50Gi
                    limits:
                        storage: 100Gi