configmapReload:
    prometheus:
        enabled: false
alertmanager: 
    persistence:
        enabled: true
        storageClass: "{{ .Values.global.nfs.storageClass }}"
        existingClaim: "{{ .Values.storage.alertmanager.name }}"
    ingress:
        enabled: false
server: 
{{  if .Values.global.tls.enabled  }}
    baseURL: "https://{{$prometheusHost}}.{{ .Values.global.domain }}"
{{ else }}
    baseURL: "http://{{$prometheusHost}}.{{ .Values.global.domain }}"
{{ end }}
    persistentVolume:
        enabled: true
        storageClass: "{{ .Values.global.nfs.storageClass }}"
        existingClaim: "{{ .Values.storage.prometheus.name }}"
    ingress:
        enabled: false