cleanPrometheusOperatorObjectNames: true
alertmanager:
  alertmanagerSpec:
    storage: 
        volumeClaimTemplate:
            spec:
                storageClassName: {{ .Values.global.nfs.storageClass }}
                accessModes: ["ReadWriteOnce"]
                resources:
                    requests:
                        storage: 50Gi
                    limits:
                        storage: 100Gi

{{-  if .Values.global.tls.enabled  }}
    externalUrl: "https://alerts.core.{{ .Values.global.domain }}"
{{- else }}
    externalUrl: "http://alerts.core.{{ .Values.global.domain }}"
{{- end }}
    resources: 
        requests:
            memory: 400Mi
        limits:
            memory: 2Gi

grafana:
  defaultDashboardsTimezone: {{ .Values.global.timezone }}
  adminPassword: prom-operator

prometheus:
  prometheusSpec:
    enableAdminAPI: false

{{-  if .Values.global.tls.enabled  }}
    externalUrl: "https://monitoring.core.{{ .Values.global.domain }}"
{{- else }}
    externalUrl: "http://monitoring.core.{{ .Values.global.domain }}"
{{- end }}
    resources: 
        requests:
            memory: 400Mi
        limits:
            memory: 2Gi
    storageSpec: 
        volumeClaimTemplate:
            spec:
                storageClassName: {{ .Values.global.nfs.storageClass }}
                accessModes: ["ReadWriteOnce"]
                resources:
                    requests:
                        storage: 50Gi
                    limits:
                        storage: 100Gi