authentik: {}
auth:
  authentik:
    postgresql:
      host: postgres.database.svc.cluster.local
      name: authentik
      user: authentik
  nameOverride: "authentik"
  fullnameOverride: "authentik"
  postgresql:
    enabled: false
  redis:
    enabled: true
  envFrom:
    - secretRef:
        name: authentik-env
