---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: "{{ .Values.ns.argocd }}"
spec:
  generators:
  - git:
      directories:
      - path: charts/apps/*
      repoURL: {{ .Values.gitops.url }}
      revision: "{{ .Values.gitops.revision }}"
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
  template:
    metadata:
      name: "{{`apps-{{path.basename}}`}}"
    spec:
      destination:
        namespace: "{{`{{path.basename}}`}}"
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
          - RespectIgnoreDifferences=true
      project: main
      revisionHistoryLimit: 4
      source:
        path: '{{`{{path}}`}}'
        repoURL: {{ .Values.gitops.url }}
        targetRevision: "{{ .Values.gitops.revision }}"
        helm:
            valueFiles:
              - values.yaml
              - values-{{$.Values.global.deployment}}.yaml
            values: |-
                global:
                    {{ .Values.global | toYaml | nindent 20 }}
