{{ include "git-repo" (dict 
  "name" "homelab"
  "namespace" $.Values.ns.argocd 
  "sshkey" $.Values.gitops.sshkey
  "url" $.Values.gitops.repo
)}}



{{- range $name, $val := .Values.additionalRepos }}
{{ include "git-repo" (merge $val (dict 
  "name" $name
  "namespace" $.Values.ns.argocd
))}}
{{ end -}}