---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: "{{ .Values.ns.argocd }}"
spec:
  generators:
  - git:
      directories:
      - path: charts/apps/*
      repoURL: git@github.com:{{ .Values.gitops.repo }}.git
      revision: "{{ .Values.gitops.revision }}"
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
  template:
    metadata:
      name: "{{`apps-{{path.basename}}`}}"
    spec:
      destination:
        namespace: "{{`{{path.basename}}`}}"
        server: https://kubernetes.default.svc
      project: main``
      revisionHistoryLimit: 10
      source:
        path: '{{`{{path}}`}}'
        repoURL: git@github.com:{{ .Values.gitops.repo }}.git
        targetRevision: "{{ .Values.gitops.revision }}"
        helm:
            valueFiles:
              - values.yaml
              - values-{{$.Values.global.deployment}}.yaml
            values: |-
                global:
                    {{ .Values.global | toYaml | nindent 20 }}