---
apiVersion: v1
kind: Secret
metadata:
  name: argo-repo-main
  namespace: "{{ .Values.ns.argocd }}"
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    link.argocd.argoproj.io/external-link: "https://github.com/{{ .Values.gitops.repo }}"
stringData:
  type: git
  url: "git@github.com:{{ .Values.gitops.repo }}.git"
  sshPrivateKey: {{ .Values.gitops.sshkey | quote }}
