---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: main
  namespace: "{{ .Values.ns.argocd }}"
spec:
  description: "Main Project"
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  orphanedResources:
    warn: true
