---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: "{{ .Values.registry.image }}"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: storage
              mountPath: /var/lib/registry
          env:
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /var/lib/registry
          resources:
            requests:
              cpu: 0.1
              memory: 250Mi
      volumes:
        - name: storage
          nfs:
            server: "{{ .Values.global.nfs.server }}"
            path: "{{ .Values.global.nfs.rootPath }}/docker-registry"
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  annotations:
    metallb.universe.tf/loadBalancerIPs: "{{ .Values.registry.ip }}"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: registry
