apiVersion: v2
name: nextcloud
description: An applications service for homelab
type: application
version: 0.1.0
dependencies: []
# - name: nextcloud
#   repository: https://nextcloud.github.io/helm/
#   version: 3.5.3
