lab:
    -   mac: '3C:7C:3F:1E:B7:A0'
        name: 'tnascore1'
    -   mac: '00:A0:98:3D:7C:C8'
        name: 'kubedb'
    -   mac: 'B8:27:EB:F7:44:4E'
        name: 'pi1'
    -   mac: '9C:BF:0D:00:56:51'
        name: 'fws1'
k3s:
    -   mac: '7C:83:34:B8:7B:43'
        name: 'bee1'
        domain: home.sosnovsky.ca
    -   mac: '68:1D:EF:26:B7:6C'
        name: 'terry1'
        domain: home.sosnovsky.ca
    -   mac: '58:47:CA:71:D8:E6'
        name: 'minisf1'
        domain: home.sosnovsky.ca
    -   mac: '00:A0:98:17:B2:64'
        name: 'tnas1'
hub:
    -   mac: 'E4:5F:01:A2:8D:BC'
        name: 'castle'
        domain: castle.home.sosnovsky.ca
    -   mac: 'DC:A6:32:92:B2:79'
        name: 'basement'
        domain: basement.home.sosnovsky.ca
    -   mac: '4E:F6:9C:7C:56:33'
        name: 'flic'
cam:
    -   name: 'korie'
        mac: '01:9c:8e:cd:25:83:1f'
    -   name: 'eddie'
        mac: '01:a0:60:32:03:86:8a'
    -   name: 'doorbell'
        mac: '01:48:9e:9d:4a:32:80'
    -   name: 'livingroom'
        mac: '34:60:F9:D7:51:3F'