lab:
    -   mac: '3C:7C:3F:1E:B7:A0'
        name: 'tnas1'
        domain: 'tnas1.lab.local'
    -   mac: '00:A0:98:3D:7C:C8'
        name: 'kubedb'
    -   mac: 'B8:27:EB:F7:44:4E'
        name: 'pi1'
    -   mac: '9C:BF:0D:00:56:51'
        name: 'fws1'
k3s:
    -   mac: '7C:83:34:B8:7B:43'
        name: 'bee1'
        domain: home.sosnovsky.ca
    -   mac: '68:1D:EF:26:B7:6C'
        name: 'terry1'
        # domain: home.sosnovsky.ca
    -   mac: '58:47:CA:71:D8:E6'
        name: 'minisf1'
        # domain: home.sosnovsky.ca
    -   mac: '00:A0:98:17:B2:64'
        name: 'tnas1'
hub:
    -   mac: 'E4:5F:01:A2:8D:BC'
        name: 'castle'
        domain: castle.home.sosnovsky.ca
    -   mac: 'DC:A6:32:92:B2:79'
        name: 'basement'
        domain: basement.home.sosnovsky.ca
    -   mac: '4E:F6:9C:7C:56:33'
        name: 'flic'
cam:
    -   name: 'korie'
        mac: '9C:8E:CD:25:83:1F'
    -   name: 'eddie'
        mac: 'A0:60:32:03:86:8A'
    -   name: 'doorbell'
        mac: '48:9E:9D:4A:32:80'
    -   name: 'livingroom'
        mac: '34:60:F9:D7:51:3F'
    -   name: 'garage'
        mac: ''
iot:
    -   name: 'korie-lamp'
        mac: '60:74:F4:4D:B8:C5'
    -   name: 'office-strip'
        mac: 'DC:4F:22:24:0C:E4'
    -   name: 'ecobee'
        mac: '44:61:32:FC:10:EC'
    -   name: 'apollo-eddie'
        mac: '30:30:F9:DC:A8:18'
    -   name: 'apollo-office'
        mac: '30:30:F9:DA:C7:A4'
    -   name: 'apollo-laundry'
        mac: '30:30:F9:DC:BE:7C'
    -   name: 'epl-kitchen'
        mac: '64:B7:08:28:52:50'
    -   name: 'epl-livingroom'
        mac: '64:B7:08:28:56:F4'
    -   name: 'shelly-basement-living'
        mac: 'B8:D6:1A:8A:5F:F4'
    -   name: 'shelly-basement-shared'
        mac: 'B8:D6:1A:8C:4C:DC'
    -   name: 'shelly-laundry-light'
        mac: 'C8:2B:96:1D:DA:B4'
apl:
    -   name: 'hp-print'
        mac: '48:9E:BD:CB:07:E3'
    -   name: 'gm-eddie'
        mac: '20:DF:B9:71:55:9C'
    -   name: 'myq-garage'
        mac: 'CC:6A:10:8B:7D:D3'
    -   name: 'pod-korie'
        mac: '04:99:B9:86:2D:AE'
    -   name: 'pod-livingroom'
        mac: '04:99:B9:88:ED:3B'
    -   name: 'appletv-livingroom'
        mac: '48:E1:5C:5B:CB:A3'
    -   name: 'samsuntv-livingroom'
        mac: 'F0:70:4F:54:F3:F0'
router:
    -   name: 'velica-office'
        mac: '94:83:C4:41:77:BA'
    -   name: 'gl-basement'
        mac: '94:83:C4:31:D5:CE'
