argo-cd:
  configs:
    cm:
      exec.enabled: true
    params:
      server.insecure: true
      server.basehref: /
      server.rootpath: ""
  crds:
    install: true
    keep: false
  server:
    ingress:
      enabled: false
    ingressGrpc:
      enabled: false
debugger:
  enabled: false
selfapp:
  commit: "stable"
  repo: "asosnovsky/homelab"
  sshkey: ""
global:
  email: "ariel@sosnovsky.ca"
  tls:
    enabled: false
    issuer: ""
    secretName: ""
  domain: ""
  deployment: ""
  nfs:
    server: "changme"
  timezone: America/Toronto
