global:
    dns:
        primary: 
            domain: "internal"
    nfs:
        storageClassName: nfs-provider

authelia:
    appName: 'Sosnovsky Cloud'
    logLevel: info
    image: "docker.io/authelia/authelia:latest"
    enableAdminUI: true
    redis:
        image: redis:7
    pg:
        image: postgres:17.4
    configuration: 
        theme: 'dark'
        authentication_backend:
            file:
                path: '/config/users_database.yml'
                watch: true
        access_control:
            default_policy: 'two_factor'
            rules:
                -   domain: "auth{{ .Values.global.dns.primary.root }}.{{ .Values.global.dns.primary.domain }}"
                    policy: one_factor
                -   domain: "{{ .Values.global.dns.primary.domain }}"
                    policy: two_factor
        notifier:
            filesystem:
                filename: '/config/notification.txt'
        session:
            name: 'authelia_session'
            inactivity: '5m'
            expiration: '1h'
            remember_me: '1M'
            cookies:
                -   domain: '{{ .Values.global.dns.primary.domain }}'
                    authelia_url: 'https://auth{{ .Values.global.dns.primary.root }}.{{ .Values.global.dns.primary.domain }}'
        identity_providers:
            oidc:
                clients:
                    -   client_id: 'immich'
                        client_name: 'immich'
                        client_secret: '$pbkdf2-sha512$310000$Q.wxPDRHGpOuns0zDC9ZAA$R1s0k48mYelv/aSNFy6pPrVwePYjqicY9H1MUWcDwP1nMEsaiNQDMBjSuIlfW18deP5qtTNjCbTJRpM6lsmo6Q'  
                        public: false
                        authorization_policy: 'two_factor'
                        redirect_uris:
                            - 'https://immich.{{ .Values.global.dns.primary.root }}.{{ .Values.global.dns.primary.domain }}/auth/login'
                            - 'https://immich.{{ .Values.global.dns.primary.root }}.{{ .Values.global.dns.primary.domain }}/user-settings'
                            - 'app.immich:///oauth-callback'
                        scopes:
                            - 'openid'
                            - 'profile'
                            - 'email'
                        userinfo_signed_response_alg: 'none'
                        token_endpoint_auth_method: 'client_secret_post'