global:
    dns:
        primary: 
            domain: "internal"
    nfs:
        storageClassName: nfs-provider

authelia:
    appName: 'Sosnovsky Cloud'
    logLevel: info
    image: "docker.io/authelia/authelia:latest"
    enableAdminUI: true
    redis:
        image: redis:7
    pg:
        image: postgres:17.4
    configuration: 
        theme: 'dark'
        authentication_backend:
            file:
                path: '/config/users_database.yml'
                watch: true
        access_control:
            default_policy: 'two_factor'
            rules:
                -   domain: "auth.{{ .Values.global.dns.primary.domain }}"
                    policy: one_factor
                -   domain: "{{ .Values.global.dns.primary.domain }}"
                    policy: two_factor
        notifier:
            filesystem:
                filename: '/config/notification.txt'
        session:
            name: 'authelia_session'
            inactivity: '5m'
            expiration: '1h'
            remember_me: '1M'
            cookies:
                -   domain: '{{ .Values.global.dns.primary.domain }}'
                    authelia_url: 'https://auth.{{ .Values.global.dns.primary.domain }}'