---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dummy-app-2
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: name
          image: nginxdemos/hello
          resources:
            limits:
              memory: 1Gi
          ports:
            - containerPort: 80