---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.authelia.secret.existingSecret }}"
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: SESSION_ENCRYPTION_KEY,REDIS_PASSWORD,JWT_TOKEN,STORAGE_ENCRYPTION_KEY
data:
  dummy_values: ""
type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.authelia.secret.existingSecret }}-db"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: chart-database
  target:
    name: "{{ .Values.authelia.secret.existingSecret }}"
    creationPolicy: Merge
  data:
    - secretKey: "STORAGE_PASSWORD"
      remoteRef:
        key: "password.pg.authelia"
        property: password

