authelia:
  configMap:
    notifier:
      disable_startup_check: false
      smtp:
        enabled: true
      filesystem:
        enabled: false
  ingress:
    enabled: true
    certManager: true
    tls:
      enabled: true
    traefikCRD:
      enabled: true
      disableIngressRoute: true
      sticky: true
      middlewares:
        chains:
          ingressRoute:
            before:
              - name: "https-redirect"
                namespace: "apps-ingresses"
