authelia:
  domain: "changeme"
  nameOverride: main-authelia
  image:
    registry: ghcr.io
    repository: authelia/authelia
    tag: ""
    pullPolicy: IfNotPresent

  ingress:
    enabled: true
    annotations: {}
    certManager: true
    className: traefik
    subdomain: auth.core
    tls:
      enabled: false
      secret: authelia-tls
    traefikCRD:
      enabled: true
      disableIngressRoute: false
      sticky: true

  pod:
    kind: DaemonSet
    replicas: 1
    revisionHistoryLimit: 1
    env:
      - name: TZ
        value: America/Toronto

    resources:
      limits:
        cpu: "4.00"
        memory: 125Mi
      requests:
        cpu: "0.25"
        memory: 50Mi
  persistence:
    enabled: true
    readOnly: false
    accessModes:
      - ReadWriteMany
    size: 100Mi

  configMap:
    enabled: true
    theme: dark
    default_2fa_method: totp

    access_control:
      secret:
        enabled: true
        key: configuration.acl.yaml
      ## Default policy can either be 'bypass', 'one_factor', 'two_factor' or 'deny'. It is the policy applied to any
      default_policy: two_factor
      networks: []
      # networks:
      # - name: private
      #   networks:
      #   - 10.0.0.0/8
      #   - 172.16.0.0/12
      #   - 192.168.0.0/16
      # - name: vpn
      #   networks:
      #   - 10.9.0.0/16
      rules: []
      # rules:
      # - domain_regex: '^.*\.example.com$'
      #   policy: bypass
      # - domain: public.example.com
      #   policy: bypass
      # - domain: "*.example.com"
      #   policy: bypass
      #   methods:
      #   - OPTIONS
      # - domain: secure.example.com
      #   policy: one_factor
      #   networks:
      #   - private
      #   - vpn
      #   - 192.168.1.0/24
      #   - 10.0.0.1
      # - domain:
      #   - secure.example.com
      #   - private.example.com
      #   policy: two_factor
      # - domain: singlefactor.example.com
      #   policy: one_factor
      # - domain: "mx2.mail.example.com"
      #   subject: "group:admins"
      #   policy: deny
      # - domain: "*.example.com"
      #   subject:
      #   - "group:admins"
      #   - "group:moderators"
      #   policy: two_factor
      # - domain: dev.example.com
      #   resources:
      #   - "^/groups/dev/.*$"
      #   subject: "group:dev"
      #   policy: two_factor
      # - domain: dev.example.com
      #   resources:
      #   - "^/users/john/.*$"
      #   subject:
      #   - ["group:dev", "user:john"]
      #   - "group:admins"
      #   policy: two_factor
      # - domain: "{user}.example.com"
      #   policy: bypass

    authentication_backend:
      ldap:
        enabled: false
      file:
        enabled: true
        path: /config/users_database.yml
        watch: true
        search:
          email: true
          case_insensitive: true

    storage:
      postgres:
        enabled: true
        host: postgres.chart-database.svc.cluster.local
        port: 5432
        database: authelia
        schema: public
        username: authelia
        timeout: 5s

    notifier:
      disable_startup_check: true
      smtp:
        enabled: false
      filesystem:
        enabled: true
        filename: /config/notification.txt

    session:
      name: authelia_session
      same_site: lax
      expiration: 1h
      inactivity: 5m
      remember_me_duration: 1M
      redis:
        enabled: true
        enabledSecret: true
        host: redis-authelia-headless.apps-authelia.svc.cluster.local
        port: 6379
        database_index: 0
        maximum_active_connections: 8
        minimum_idle_connections: 0

  secret:
    existingSecret: authelia
    mountPath: /secrets
    excludeVolumeAndMounts: false

    storage:
      key: STORAGE_PASSWORD
    session:
      key: SESSION_ENCRYPTION_KEY
    redis:
      key: REDIS_PASSWORD
    smtp:
      key: SMTP_PASSWORD
    jwt:
      key: JWT_TOKEN
    storageEncryptionKey:
      key: STORAGE_ENCRYPTION_KEY
redis:
  image:
    registry: docker.io
    repository: bitnami/redis
    tag: 7.0.10-debian-11-r2
    pullPolicy: IfNotPresent
  fullnameOverride: "redis-authelia"
  architecture: replication
  auth:
    enabled: true
    existingSecret: "authelia"
    existingSecretPasswordKey: "REDIS_PASSWORD"
    usePasswordFiles: false

  master:
    count: 1
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    persistence:
      enabled: true
      size: "8Gi"
      storageClass: ""
      accessModes:
        - ReadWriteOnce
    service:
      type: ClusterIP
      ports:
        redis: 6379

  replica:
    replicaCount: 1
    containerPorts:
      redis: 6379
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 8Gi
    service:
      type: ClusterIP
      ports:
        redis: 6379
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 4
      targetCPU: "80"
      targetMemory: "80"
