---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "nfs-generic"
  namespace: "{{ .Release.Namespace }}"
spec:
  project: meta-infrastructure
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/"
    targetRevision: "{{ .Values.chartVersions.nfs }}"
    helm:
      releaseName: nfs-subdir-external-provisioner
      parameters:
        - name: nfs.server
          value: "{{ .Values.global.nfs.server }}"
        - name: nfs.path
          value: "{{ .Values.nfs.share }}"
        - name: storageClass.name
          value: "{{ .Values.global.nfsStorageClass }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: "nfs-subdir-external-provisioner"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
