---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "external-secrets"
  namespace: "{{ .Release.Namespace }}"
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: "https://charts.external-secrets.io"
    targetRevision: "0.7.2"
    helm:
      values: |-
        installCRDs: true
      releaseName: external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: "external-secrets"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
