---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "nfs-generic"
  namespace: "{{ .Release.Namespace }}"
spec:
  project: meta-infrastructure
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/"
    targetRevision: "4.2.0"
    helm:
      releaseName: nfs-subdir-external-provisioner
      values: |-
        nfs:
          server: {{ .Values.nfs.server }}
          path: {{ .Values.nfs.share }}
        storageClass:
          name: "nfs-generic"
  destination:
    server: https://kubernetes.default.svc
    namespace: "nfs-subdir-external-provisioner"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
